import { createHash } from "node:crypto";
import type { AuditPrincipal, AuditSink, Clock, DataClassification, IdFactory } from "../../../packages/security-contracts/src/index.js";
import type { AuthorizationService } from "../../authorization/src/authorization-service.js";
import type { SessionContext } from "../../identity/src/session-service.js";
import type { Permission, PermissionAudience, PermissionAudienceCode } from "../../permission/src/permission-service.js";
import type { Verification, VerificationField, VersionedEntityReference } from "../../verification/src/verification-service.js";

export interface PublicationTargetPolicySnapshot {
  readonly targetId: string; readonly channelId: string; readonly targetStatus: "ACTIVE" | "INACTIVE"; readonly channelStatus: "ACTIVE" | "INACTIVE";
  readonly targetPolicyVersion: string; readonly channelPolicyVersion: string; readonly allowedLanguages: readonly string[];
  readonly allowedAudienceCodes: readonly PermissionAudienceCode[]; readonly allowedFields: readonly VerificationField[]; readonly allowedMedia: readonly string[];
}
export interface RepresentationSourceSnapshot {
  readonly teamId: string; readonly subjectRef: VersionedEntityReference; readonly provenanceRef: VersionedEntityReference; readonly canonicalContent: Readonly<Record<string, unknown>>;
  readonly fieldScope: readonly VerificationField[]; readonly mediaScope: readonly string[]; readonly creatorId: string; readonly editorIds: readonly string[];
  readonly classification: DataClassification; readonly privacyValidated: true;
}
export interface RepresentationMaterial {
  readonly subjectRef: VersionedEntityReference; readonly canonicalContent: Readonly<Record<string, unknown>>; readonly fieldScope: readonly VerificationField[];
  readonly mediaScope: readonly string[]; readonly language: string; readonly audience: PermissionAudience; readonly targetId: string; readonly channelId: string;
  readonly targetPolicyVersion: string; readonly channelPolicyVersion: string; readonly provenanceRef: VersionedEntityReference; readonly creatorId: string; readonly editorIds: readonly string[];
  readonly sourceClassification?: DataClassification;
}
export interface ImmutableRepresentationSnapshot extends RepresentationMaterial {
  readonly id: string; readonly version: number; readonly teamId: string; readonly checksum: string; readonly createdAt: string;
  readonly classification: DataClassification; readonly policyVersion: string;
}
export type PublicationApprovalStatus = "REQUESTED" | "UNDER_REVIEW" | "APPROVED" | "REJECTED" | "REVOKED" | "EXPIRED";
export type PublicationApprovalDecision = "APPROVED" | "REJECTED";
export interface ApprovalStatusEntry { readonly status: PublicationApprovalStatus; readonly actorId: string; readonly reason: string; readonly occurredAt: string }
export interface ApprovalAssignmentEntry { readonly actorId: string; readonly previousApproverActorId?: string; readonly newApproverActorId?: string; readonly reason: string; readonly occurredAt: string }
export interface ApprovalDecisionEntry { readonly actorId: string; readonly decision: PublicationApprovalDecision | "REVOKED" | "EXPIRED"; readonly reason: string; readonly occurredAt: string }
export interface PublicationApproval {
  readonly id: string; readonly version: number; readonly canonicalVersion: string; readonly teamId: string; readonly status: PublicationApprovalStatus;
  readonly representationId: string; readonly representationVersion: number; readonly representationChecksum: string;
  readonly subjectRef: VersionedEntityReference; readonly targetId: string; readonly channelId: string; readonly targetPolicyVersion: string; readonly channelPolicyVersion: string;
  readonly approvedFieldScope: readonly VerificationField[]; readonly approvedMediaScope: readonly string[]; readonly audience: PermissionAudience; readonly language: string;
  readonly verificationId: string; readonly verificationRevision: number; readonly permissionId: string; readonly permissionRevision: number;
  readonly requesterActorId: string; readonly assignedApproverActorId: string | undefined; readonly decisionActorId?: string; readonly decision?: PublicationApprovalDecision | "REVOKED" | "EXPIRED"; readonly reason?: string;
  readonly requestedAt: string; readonly reviewStartedAt?: string; readonly decisionAt?: string; readonly effectiveAt?: string; readonly expiresAt: string; readonly revokedAt?: string; readonly revocationReason?: string;
  readonly predecessorApprovalId?: string; readonly assignmentHistory: readonly ApprovalAssignmentEntry[]; readonly decisionHistory: readonly ApprovalDecisionEntry[]; readonly statusHistory: readonly ApprovalStatusEntry[];
  readonly classification: DataClassification; readonly policyVersion: string; readonly auditMetadata: Readonly<{ readonly correlationId: string; readonly policyVersion: string; readonly rawContactIncluded: false }>;
}
export interface ApprovalQueueFilters { readonly status?: PublicationApprovalStatus; readonly assignment?: "ASSIGNED" | "UNASSIGNED"; readonly targetId?: string; readonly requestedFrom?: string; readonly expiresBefore?: string }
export interface ApprovalReviewContext { readonly approval: PublicationApproval; readonly representation: ImmutableRepresentationSnapshot; readonly verificationValid: boolean; readonly permissionValid: boolean; readonly targetPolicyValid: boolean; readonly actorEligible: boolean; readonly actorConflictReasonCodes: readonly string[]; readonly privacyResult: "MASKED_AND_MINIMIZED"; readonly safeReasonCodes: readonly string[] }
export interface EffectiveApprovalDecision { readonly effective: boolean; readonly approvalId: string; readonly approvalVersion: number; readonly checkedAt: string; readonly effectiveScope: Readonly<{ readonly targetId: string; readonly channelId: string; readonly fieldScope: readonly VerificationField[]; readonly mediaScope: readonly string[]; readonly audience: PermissionAudience; readonly language: string }>; readonly expiresAt: string; readonly reasonCodes: readonly string[] }

interface Context { readonly actor: SessionContext; readonly purpose: "PURPOSE_PUBLICATION_APPROVAL"; readonly correlationId: string; readonly requestId?: string }
interface Dependencies {
  readonly authorizationService: AuthorizationService; readonly auditSink: AuditSink; readonly clock: Clock; readonly idFactory: IdFactory; readonly policyVersion: string;
  readonly verificationResolver: (verificationId: string) => Verification | undefined; readonly permissionResolver: (permissionId: string) => Permission | undefined;
  readonly targetPolicyResolver: (targetId: string, channelId: string) => PublicationTargetPolicySnapshot | undefined;
  readonly representationSourceResolver: (teamId: string, subjectRef: VersionedEntityReference, provenanceRef: VersionedEntityReference) => RepresentationSourceSnapshot | undefined;
  readonly puaEligibilityResolver: (principalId: string, teamId: string, purpose: string) => boolean;
  readonly schedulerEligibilityResolver: (principalId: string, teamId: string, purpose: string) => boolean;
}
interface IdempotencyRecord { readonly fingerprint: string; readonly kind: "REPRESENTATION" | "APPROVAL"; readonly id: string; readonly version: number }
interface DependencyResult { readonly verification: Verification; readonly permission: Permission; readonly policy: PublicationTargetPolicySnapshot; readonly expiresAt: string }

function deepFreeze(value: unknown): void { if (value !== null && typeof value === "object" && !Object.isFrozen(value)) { Object.values(value).forEach(deepFreeze); Object.freeze(value); } }
function immutable<T>(value: T): T { const snapshot = structuredClone(value); deepFreeze(snapshot); return snapshot; }
function canonical(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonical); if (value !== null && typeof value === "object") return Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, nested]) => [key, canonical(nested)])); return value; }
function principal(actor: SessionContext): AuditPrincipal { return { id: actor.principalId, type: actor.principalType, roles: actor.roles, ...(actor.teamId === undefined ? {} : { teamId: actor.teamId }), sessionId: actor.id }; }
function sameRef(left: VersionedEntityReference, right: VersionedEntityReference): boolean { return left.entityType === right.entityType && left.entityId === right.entityId && left.version === right.version; }
function sameArray(left: readonly string[], right: readonly string[]): boolean { return [...left].sort().join("|") === [...right].sort().join("|"); }
function maxClassification(left: DataClassification, right: DataClassification): DataClassification { const values: readonly DataClassification[] = ["PUBLIC_APPROVED", "INTERNAL", "CONFIDENTIAL_BUSINESS", "RESTRICTED_PERSONAL", "RESTRICTED_SECURITY"]; return values[Math.max(values.indexOf(left), values.indexOf(right))]!; }
function publicContentIsSafe(content: Readonly<Record<string, unknown>>): boolean { const serialized = JSON.stringify(content); return !/(?:[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}|\+?\d[\d\s().-]{6,}\d|"(?:email|phone|contactValue)"\s*:)/iu.test(serialized); }

export function computeRepresentationChecksum(input: RepresentationMaterial): string {
  const material: RepresentationMaterial = { subjectRef: input.subjectRef, canonicalContent: input.canonicalContent, fieldScope: input.fieldScope, mediaScope: input.mediaScope, language: input.language, audience: input.audience, targetId: input.targetId, channelId: input.channelId, targetPolicyVersion: input.targetPolicyVersion, channelPolicyVersion: input.channelPolicyVersion, provenanceRef: input.provenanceRef, creatorId: input.creatorId, editorIds: input.editorIds, ...(input.sourceClassification === undefined ? {} : { sourceClassification: input.sourceClassification }) };
  return `sha256:${createHash("sha256").update(JSON.stringify(canonical(material))).digest("hex")}`;
}

export class PublicationApprovalService {
  readonly #authorization: AuthorizationService; readonly #audit: AuditSink; readonly #clock: Clock; readonly #idFactory: IdFactory; readonly #policyVersion: string;
  readonly #verificationResolver: Dependencies["verificationResolver"]; readonly #permissionResolver: Dependencies["permissionResolver"]; readonly #targetPolicyResolver: Dependencies["targetPolicyResolver"]; readonly #representationSourceResolver: Dependencies["representationSourceResolver"]; readonly #puaEligibilityResolver: Dependencies["puaEligibilityResolver"]; readonly #schedulerEligibilityResolver: Dependencies["schedulerEligibilityResolver"];
  readonly #representations = new Map<string, ImmutableRepresentationSnapshot>(); readonly #representationHistory = new Map<string, ImmutableRepresentationSnapshot[]>();
  readonly #approvals = new Map<string, PublicationApproval>(); readonly #approvalHistory = new Map<string, PublicationApproval[]>(); readonly #idempotency = new Map<string, IdempotencyRecord>();

  public constructor(dependencies: Dependencies) { this.#authorization = dependencies.authorizationService; this.#audit = dependencies.auditSink; this.#clock = dependencies.clock; this.#idFactory = dependencies.idFactory; this.#policyVersion = dependencies.policyVersion; this.#verificationResolver = dependencies.verificationResolver; this.#permissionResolver = dependencies.permissionResolver; this.#targetPolicyResolver = dependencies.targetPolicyResolver; this.#representationSourceResolver = dependencies.representationSourceResolver; this.#puaEligibilityResolver = dependencies.puaEligibilityResolver; this.#schedulerEligibilityResolver = dependencies.schedulerEligibilityResolver; }

  public createRepresentationSnapshot(request: Context & RepresentationMaterial & { readonly representationId?: string; readonly expectedPreviousVersion?: number; readonly checksum: string; readonly reason: string; readonly idempotencyKey: string }): ImmutableRepresentationSnapshot {
    this.#reason(request.reason); const teamId = this.#team(request.actor); this.#authorize(request, "publication.representation.create", "ImmutableRepresentationSnapshot", request.representationId ?? "new", teamId);
    const source = this.#authoritativeRepresentationSource(teamId, request); const authoritativeMaterial: RepresentationMaterial = { subjectRef: source.subjectRef, canonicalContent: source.canonicalContent, fieldScope: source.fieldScope, mediaScope: source.mediaScope, language: request.language, audience: request.audience, targetId: request.targetId, channelId: request.channelId, targetPolicyVersion: request.targetPolicyVersion, channelPolicyVersion: request.channelPolicyVersion, provenanceRef: source.provenanceRef, creatorId: source.creatorId, editorIds: source.editorIds, sourceClassification: source.classification }; this.#validateRepresentationMaterial(authoritativeMaterial); const expectedChecksum = computeRepresentationChecksum(authoritativeMaterial); if (request.checksum !== expectedChecksum) throw new Error("REPRESENTATION_CHECKSUM_MISMATCH");
    const fingerprint = JSON.stringify({ action: "REPRESENTATION", representationId: request.representationId, expectedPreviousVersion: request.expectedPreviousVersion, material: canonical(authoritativeMaterial), checksum: request.checksum }); const replay = this.#replayRepresentation(request, fingerprint); if (replay !== undefined) return replay;
    let id: string; let version: number;
    if (request.representationId === undefined) { if (request.expectedPreviousVersion !== undefined) throw new Error("EXPECTED_VERSION_MISMATCH"); id = this.#idFactory(); version = 1; }
    else { const current = this.#representations.get(request.representationId); if (current === undefined) throw new Error("NOT_FOUND"); if (request.expectedPreviousVersion !== current.version) throw new Error("EXPECTED_VERSION_MISMATCH"); id = current.id; version = current.version + 1; }
    const snapshot = immutable<ImmutableRepresentationSnapshot>({ id, version, teamId, subjectRef: authoritativeMaterial.subjectRef, canonicalContent: authoritativeMaterial.canonicalContent, fieldScope: [...new Set(authoritativeMaterial.fieldScope)], mediaScope: [...new Set(authoritativeMaterial.mediaScope)], language: authoritativeMaterial.language, audience: authoritativeMaterial.audience, targetId: authoritativeMaterial.targetId, channelId: authoritativeMaterial.channelId, targetPolicyVersion: authoritativeMaterial.targetPolicyVersion, channelPolicyVersion: authoritativeMaterial.channelPolicyVersion, provenanceRef: authoritativeMaterial.provenanceRef, creatorId: authoritativeMaterial.creatorId, editorIds: [...new Set(authoritativeMaterial.editorIds)], sourceClassification: source.classification, checksum: request.checksum, createdAt: this.#clock().toISOString(), classification: source.classification, policyVersion: this.#policyVersion });
    this.#representations.set(id, snapshot); this.#representationHistory.set(id, [...(this.#representationHistory.get(id) ?? []), snapshot]); this.#remember(request, fingerprint, "REPRESENTATION", id, version); this.#auditEvent("REPRESENTATION_SNAPSHOT_CREATED", "publication.representation.create", "ImmutableRepresentationSnapshot", id, version, request, snapshot.classification, request.reason, { representationVersion: version, checksum: snapshot.checksum, targetId: snapshot.targetId, channelId: snapshot.channelId, idempotencyOutcome: "CREATED", privacyValidation: "PASSED", rawContactIncluded: false }); return snapshot;
  }

  public createApprovalRequest(request: Context & { readonly representationId: string; readonly representationVersion: number; readonly representationChecksum: string; readonly subjectRef: VersionedEntityReference; readonly verificationId: string; readonly verificationVersion: number; readonly permissionId: string; readonly permissionVersion: number; readonly expectedVersion: 0; readonly predecessorApprovalId?: string; readonly reason: string; readonly idempotencyKey: string }): PublicationApproval {
    this.#reason(request.reason); const teamId = this.#team(request.actor); this.#authorize(request, "publication.approval.request", "PublicationApproval", "new", teamId);
    const fingerprint = JSON.stringify({ action: "REQUEST", representationId: request.representationId, representationVersion: request.representationVersion, representationChecksum: request.representationChecksum, subjectRef: request.subjectRef, verificationId: request.verificationId, verificationVersion: request.verificationVersion, permissionId: request.permissionId, permissionVersion: request.permissionVersion, predecessorApprovalId: request.predecessorApprovalId }); const replay = this.#replayApproval(request, fingerprint); if (replay !== undefined) return replay;
    if (request.expectedVersion !== 0) throw new Error("EXPECTED_VERSION_MISMATCH"); const representation = this.#exactRepresentation(request.representationId, request.representationVersion, request.representationChecksum, teamId); if (!sameRef(representation.subjectRef, request.subjectRef)) throw new Error("SUBJECT_REVISION_CHANGED");
    if (request.predecessorApprovalId !== undefined) { const predecessor = this.#approvals.get(request.predecessorApprovalId); if (predecessor?.teamId !== teamId || !sameRef(predecessor.subjectRef, representation.subjectRef) || !new Set<PublicationApprovalStatus>(["REJECTED", "REVOKED", "EXPIRED"]).has(predecessor.status)) throw new Error("APPROVAL_NOT_EFFECTIVE"); }
    const dependencies = this.#dependencies(representation, request.verificationId, request.verificationVersion, request.permissionId, request.permissionVersion);
    const occurredAt = this.#clock().toISOString(); const classification = maxClassification(representation.classification, maxClassification(dependencies.verification.classification, dependencies.permission.classification));
    const approval = immutable<PublicationApproval>({ id: this.#idFactory(), version: 1, canonicalVersion: "publication-approval-v1", teamId, status: "REQUESTED", representationId: representation.id, representationVersion: representation.version, representationChecksum: representation.checksum, subjectRef: representation.subjectRef, targetId: representation.targetId, channelId: representation.channelId, targetPolicyVersion: representation.targetPolicyVersion, channelPolicyVersion: representation.channelPolicyVersion, approvedFieldScope: representation.fieldScope, approvedMediaScope: representation.mediaScope, audience: representation.audience, language: representation.language, verificationId: dependencies.verification.id, verificationRevision: dependencies.verification.version, permissionId: dependencies.permission.id, permissionRevision: dependencies.permission.version, requesterActorId: request.actor.principalId, assignedApproverActorId: undefined, requestedAt: occurredAt, expiresAt: dependencies.expiresAt, ...(request.predecessorApprovalId === undefined ? {} : { predecessorApprovalId: request.predecessorApprovalId }), assignmentHistory: [], decisionHistory: [], statusHistory: [{ status: "REQUESTED", actorId: request.actor.principalId, reason: request.reason, occurredAt }], classification, policyVersion: this.#policyVersion, auditMetadata: { correlationId: request.correlationId, policyVersion: this.#policyVersion, rawContactIncluded: false } });
    this.#storeApproval(approval); this.#remember(request, fingerprint, "APPROVAL", approval.id, approval.version); this.#auditEvent("PUBLICATION_APPROVAL_REQUESTED", "publication.approval.request", "PublicationApproval", approval.id, approval.version, request, approval.classification, request.reason, { representationId: approval.representationId, representationVersion: approval.representationVersion, prerequisiteEvaluation: "PASSED", idempotencyOutcome: "CREATED", queueEntered: true, rawContactIncluded: false }); return approval;
  }

  public assignOrClaimApprover(request: Context & { readonly approvalId: string; readonly expectedVersion: number; readonly assigneeActorId: string; readonly reason: string; readonly idempotencyKey: string }): PublicationApproval {
    this.#reason(request.reason); const current = this.#scopedApproval(request, request.approvalId); this.#assertEligible(request.actor, current, request); this.#authorizeApproval(request, "publication.approval.claim", current);
    const fingerprint = JSON.stringify({ action: "CLAIM", approvalId: current.id, expectedVersion: request.expectedVersion, assigneeActorId: request.assigneeActorId, reason: request.reason }); const replay = this.#replayApproval(request, fingerprint, true, (prior) => { if (current.assignedApproverActorId !== request.assigneeActorId || prior.assignedApproverActorId !== request.assigneeActorId) throw new Error("APPROVAL_ASSIGNMENT_REQUIRED"); this.#assertEligibleActorId(request.assigneeActorId, current, request); this.#assertNoConflict(request.assigneeActorId, current, request); }); if (replay !== undefined) return replay;
    this.#version(current, request.expectedVersion); if ((current.status !== "REQUESTED" && current.status !== "UNDER_REVIEW") || current.assignedApproverActorId !== undefined) throw new Error("STATE_TRANSITION_INVALID"); if (!this.#puaEligibilityResolver(request.assigneeActorId, current.teamId, request.purpose)) throw new Error("APPROVER_NOT_ELIGIBLE"); this.#assertNoConflict(request.assigneeActorId, current, request);
    const occurredAt = this.#clock().toISOString(); const entry = immutable<ApprovalAssignmentEntry>({ actorId: request.actor.principalId, newApproverActorId: request.assigneeActorId, reason: request.reason, occurredAt });
    const updated = this.#replaceApproval(current, request, { status: "UNDER_REVIEW", assignedApproverActorId: request.assigneeActorId, ...(current.reviewStartedAt === undefined ? { reviewStartedAt: occurredAt } : {}), assignmentHistory: [...current.assignmentHistory, entry] }, "PUBLICATION_APPROVAL_ASSIGNED", "publication.approval.claim", request.reason, { newApproverActorId: request.assigneeActorId, idempotencyOutcome: "CREATED" }); this.#remember(request, fingerprint, "APPROVAL", updated.id, updated.version); return updated;
  }

  public reassignOrReleaseApprover(request: Context & { readonly approvalId: string; readonly expectedVersion: number; readonly assigneeActorId?: string; readonly reason: string; readonly idempotencyKey: string }): PublicationApproval {
    this.#reason(request.reason); const current = this.#scopedApproval(request, request.approvalId); this.#assertEligible(request.actor, current, request); this.#authorizeApproval(request, "publication.approval.assign", current);
    const fingerprint = JSON.stringify({ action: "REASSIGN_RELEASE", approvalId: current.id, expectedVersion: request.expectedVersion, assigneeActorId: request.assigneeActorId, reason: request.reason }); const replay = this.#replayApproval(request, fingerprint, true, (prior) => { if (prior.assignmentHistory.at(-1)?.actorId !== request.actor.principalId || prior.assignedApproverActorId !== request.assigneeActorId || current.assignedApproverActorId !== request.assigneeActorId) throw new Error("APPROVAL_ASSIGNMENT_REQUIRED"); if (request.assigneeActorId !== undefined) { this.#assertEligibleActorId(request.assigneeActorId, current, request); this.#assertNoConflict(request.assigneeActorId, current, request); } }); if (replay !== undefined) return replay;
    if (current.assignedApproverActorId !== request.actor.principalId) throw new Error("APPROVAL_ASSIGNMENT_REQUIRED"); this.#version(current, request.expectedVersion); if (current.status !== "UNDER_REVIEW") throw new Error("STATE_TRANSITION_INVALID"); if (request.assigneeActorId !== undefined) { if (!this.#puaEligibilityResolver(request.assigneeActorId, current.teamId, request.purpose)) throw new Error("APPROVER_NOT_ELIGIBLE"); this.#assertNoConflict(request.assigneeActorId, current, request); }
    const entry = immutable<ApprovalAssignmentEntry>({ actorId: request.actor.principalId, previousApproverActorId: current.assignedApproverActorId, ...(request.assigneeActorId === undefined ? {} : { newApproverActorId: request.assigneeActorId }), reason: request.reason, occurredAt: this.#clock().toISOString() });
    const updated = this.#replaceApproval(current, request, { ...(request.assigneeActorId === undefined ? { assignedApproverActorId: undefined } : { assignedApproverActorId: request.assigneeActorId }), assignmentHistory: [...current.assignmentHistory, entry] }, "PUBLICATION_APPROVAL_ASSIGNMENT_CHANGED", "publication.approval.assign", request.reason, { previousApproverActorId: current.assignedApproverActorId, ...(request.assigneeActorId === undefined ? { assignmentOutcome: "RELEASED" } : { newApproverActorId: request.assigneeActorId, assignmentOutcome: "REASSIGNED" }), idempotencyOutcome: "CREATED" }); this.#remember(request, fingerprint, "APPROVAL", updated.id, updated.version); return updated;
  }

  public decideApproval(request: Context & { readonly approvalId: string; readonly expectedVersion: number; readonly decision: PublicationApprovalDecision; readonly reason: string; readonly idempotencyKey: string; readonly breakGlass?: boolean }): PublicationApproval {
    this.#reason(request.reason); const current = this.#scopedApproval(request, request.approvalId); this.#assertEligible(request.actor, current, request); if (request.breakGlass === true) { this.#deny(current, request, "FORBIDDEN"); throw new Error("FORBIDDEN"); } this.#authorizeApproval(request, "publication.approval.decide", current, request.reason);
    const fingerprint = JSON.stringify({ action: "DECIDE", approvalId: current.id, expectedVersion: request.expectedVersion, decision: request.decision, reason: request.reason }); const replay = this.#replayApproval(request, fingerprint, true, (prior) => { if (prior.decisionActorId !== request.actor.principalId || current.decisionActorId !== request.actor.principalId) throw new Error("APPROVAL_ASSIGNMENT_REQUIRED"); this.#assertNoConflict(request.actor.principalId, current, request); }); if (replay !== undefined) return replay;
    this.#version(current, request.expectedVersion); if (current.status !== "REQUESTED" && current.status !== "UNDER_REVIEW") throw new Error("STATE_TRANSITION_INVALID"); if (request.decision === "APPROVED" && current.status !== "UNDER_REVIEW") throw new Error("APPROVAL_ASSIGNMENT_REQUIRED");
    this.#assertNoConflict(request.actor.principalId, current, request); let assignmentHistory = current.assignmentHistory; let assignedApproverActorId = current.assignedApproverActorId;
    if (current.status === "REQUESTED" && request.decision === "REJECTED") { assignedApproverActorId = request.actor.principalId; assignmentHistory = [...assignmentHistory, immutable({ actorId: request.actor.principalId, newApproverActorId: request.actor.principalId, reason: "Direct rejection review", occurredAt: this.#clock().toISOString() })]; }
    if (assignedApproverActorId !== request.actor.principalId) throw new Error("APPROVAL_ASSIGNMENT_REQUIRED"); const representation = this.#exactRepresentation(current.representationId, current.representationVersion, current.representationChecksum, current.teamId); this.#dependencies(representation, current.verificationId, current.verificationRevision, current.permissionId, current.permissionRevision);
    const occurredAt = this.#clock().toISOString(); const entry = immutable<ApprovalDecisionEntry>({ actorId: request.actor.principalId, decision: request.decision, reason: request.reason, occurredAt });
    const updated = this.#replaceApproval(current, request, { status: request.decision, assignedApproverActorId, assignmentHistory, decisionActorId: request.actor.principalId, decision: request.decision, reason: request.reason, decisionAt: occurredAt, ...(request.decision === "APPROVED" ? { effectiveAt: occurredAt } : {}), decisionHistory: [...current.decisionHistory, entry] }, "PUBLICATION_APPROVAL_DECIDED", "publication.approval.decide", request.reason, { mfaResult: "VERIFIED", reasonRecorded: true, idempotencyOutcome: "CREATED" }); this.#remember(request, fingerprint, "APPROVAL", updated.id, updated.version); return updated;
  }

  public revokeApproval(request: Context & { readonly approvalId: string; readonly expectedVersion: number; readonly reason: string; readonly impactScope: readonly string[]; readonly idempotencyKey: string }): PublicationApproval {
    this.#reason(request.reason); const current = this.#scopedApproval(request, request.approvalId); this.#assertEligible(request.actor, current, request); this.#assertNoConflict(request.actor.principalId, current, request); this.#authorizeApproval(request, "publication.approval.revoke", current, request.reason);
    const fingerprint = JSON.stringify({ action: "REVOKE", approvalId: current.id, expectedVersion: request.expectedVersion, reason: request.reason, impactScope: request.impactScope }); const replay = this.#replayApproval(request, fingerprint, false); if (replay !== undefined) return replay;
    this.#version(current, request.expectedVersion); if (current.status !== "APPROVED" || request.impactScope.length === 0) throw new Error("STATE_TRANSITION_INVALID"); const occurredAt = this.#clock().toISOString(); const entry = immutable<ApprovalDecisionEntry>({ actorId: request.actor.principalId, decision: "REVOKED", reason: request.reason, occurredAt });
    const updated = this.#replaceApproval(current, request, { status: "REVOKED", decision: "REVOKED", decisionActorId: request.actor.principalId, revokedAt: occurredAt, revocationReason: request.reason, decisionHistory: [...current.decisionHistory, entry] }, "PUBLICATION_APPROVAL_REVOKED", "publication.approval.revoke", request.reason, { impactScope: request.impactScope, mfaResult: "VERIFIED", reasonRecorded: true, idempotencyOutcome: "CREATED" }); this.#remember(request, fingerprint, "APPROVAL", updated.id, updated.version); return updated;
  }

  public expireApproval(request: Context & { readonly approvalId: string; readonly expectedVersion: number; readonly idempotencyKey: string }): PublicationApproval {
    const current = this.#scopedApproval(request, request.approvalId); if (request.actor.principalType !== "SERVICE" || !request.actor.roles.includes("SVC") || !this.#schedulerEligibilityResolver(request.actor.principalId, current.teamId, request.purpose)) { this.#deny(current, request, "SERVICE_AUTHORITY_REQUIRED"); throw new Error("SERVICE_AUTHORITY_REQUIRED"); } this.#authorizeApproval(request, "publication.approval.expire", current);
    const fingerprint = JSON.stringify({ action: "EXPIRE", approvalId: current.id, expectedVersion: request.expectedVersion }); const replay = this.#replayApproval(request, fingerprint, false); if (replay !== undefined) return replay;
    this.#version(current, request.expectedVersion); if (current.status !== "APPROVED") throw new Error("STATE_TRANSITION_INVALID"); if (this.#clock().getTime() < new Date(current.expiresAt).getTime()) { this.#remember(request, fingerprint, "APPROVAL", current.id, current.version); return current; }
    const reason = "Canonical approval validity ended"; const entry = immutable<ApprovalDecisionEntry>({ actorId: request.actor.principalId, decision: "EXPIRED", reason, occurredAt: this.#clock().toISOString() }); const updated = this.#replaceApproval(current, request, { status: "EXPIRED", decision: "EXPIRED", decisionHistory: [...current.decisionHistory, entry] }, "PUBLICATION_APPROVAL_EXPIRED", "publication.approval.expire", reason, { schedulerEligibility: "VERIFIED", idempotencyOutcome: "CREATED" }); this.#remember(request, fingerprint, "APPROVAL", updated.id, updated.version); return updated;
  }

  public readApproval(request: Context & { readonly approvalId: string }): PublicationApproval { const current = this.#scopedApproval(request, request.approvalId); this.#authorize(request, "publication.approval.read", "PublicationApproval", current.id, current.teamId, current.version); return current; }
  public readApprovalHistory(request: Context & { readonly approvalId: string }): readonly PublicationApproval[] { const current = this.readApproval(request); return Object.freeze([...(this.#approvalHistory.get(current.id) ?? [])]); }
  public listApprovalQueue(request: Context & { readonly filters?: ApprovalQueueFilters }): readonly PublicationApproval[] { const teamId = this.#team(request.actor); this.#authorize(request, "publication.approval.read", "PublicationApproval", "collection", teamId); const filters = request.filters; const now = this.#clock().toISOString(); return Object.freeze([...this.#approvals.values()].filter((item) => item.teamId === teamId && item.expiresAt > now && (item.status === "REQUESTED" || item.status === "UNDER_REVIEW") && (filters?.status === undefined || item.status === filters.status) && (filters?.assignment === undefined || (filters.assignment === "ASSIGNED") === (item.assignedApproverActorId !== undefined)) && (filters?.targetId === undefined || item.targetId === filters.targetId) && (filters?.requestedFrom === undefined || item.requestedAt >= filters.requestedFrom) && (filters?.expiresBefore === undefined || item.expiresAt <= filters.expiresBefore))); }
  public getApprovalReviewContext(request: Context & { readonly approvalId: string }): ApprovalReviewContext { const approval = this.readApproval(request); const representation = this.#representation(approval.representationId, approval.representationVersion); let verificationValid = true; let permissionValid = true; let targetPolicyValid = true; const safeReasonCodes: string[] = []; try { this.#verification(representation, approval.verificationId, approval.verificationRevision); } catch (error) { verificationValid = false; safeReasonCodes.push(this.#code(error)); } try { this.#permission(representation, approval.permissionId, approval.permissionRevision, approval.verificationId, approval.verificationRevision); } catch (error) { permissionValid = false; safeReasonCodes.push(this.#code(error)); } try { this.#targetPolicy(representation); } catch (error) { targetPolicyValid = false; safeReasonCodes.push(this.#code(error)); } return immutable({ approval, representation, verificationValid, permissionValid, targetPolicyValid, actorEligible: request.actor.principalType === "HUMAN" && request.actor.roles.includes("PUA") && this.#puaEligibilityResolver(request.actor.principalId, approval.teamId, request.purpose), actorConflictReasonCodes: this.#conflicts(request.actor.principalId, approval), privacyResult: "MASKED_AND_MINIMIZED", safeReasonCodes }); }

  public checkEffectiveApproval(request: Context & { readonly approvalId: string; readonly approvalVersion: number; readonly representationId: string; readonly representationVersion: number; readonly representationChecksum: string; readonly subjectRef: VersionedEntityReference; readonly targetId: string; readonly channelId: string; readonly fieldScope: readonly VerificationField[]; readonly mediaScope: readonly string[]; readonly audience: PermissionAudience; readonly language: string; readonly verificationId: string; readonly verificationVersion: number; readonly permissionId: string; readonly permissionVersion: number; readonly targetPolicyVersion: string; readonly channelPolicyVersion: string; readonly consumerDuty: "EXECUTION" | "RECONCILIATION" }): EffectiveApprovalDecision {
    const approval = this.#scopedApproval(request, request.approvalId); if (!new Set(["EXECUTION", "RECONCILIATION"]).has(request.consumerDuty)) { this.#deny(approval, request, "FORBIDDEN"); throw new Error("FORBIDDEN"); } this.#authorize(request, "publication.approval.check-effective", "PublicationApproval", approval.id, approval.teamId, approval.version); const reasons: string[] = [];
    if (approval.version !== request.approvalVersion) reasons.push("EXPECTED_VERSION_MISMATCH"); if (approval.status !== "APPROVED") reasons.push(approval.status === "REVOKED" ? "APPROVAL_REVOKED" : approval.status === "EXPIRED" ? "APPROVAL_EXPIRED" : "APPROVAL_NOT_EFFECTIVE"); if (this.#clock().getTime() >= new Date(approval.expiresAt).getTime()) reasons.push("APPROVAL_EXPIRED");
    if (approval.representationId !== request.representationId || approval.representationVersion !== request.representationVersion) reasons.push("REPRESENTATION_CHANGED"); if (approval.representationChecksum !== request.representationChecksum) reasons.push("REPRESENTATION_CHECKSUM_MISMATCH"); if (!sameRef(approval.subjectRef, request.subjectRef)) reasons.push("SUBJECT_REVISION_CHANGED");
    if (approval.targetId !== request.targetId) reasons.push("TARGET_NOT_ALLOWED"); if (approval.channelId !== request.channelId) reasons.push("CHANNEL_NOT_ALLOWED"); if (!sameArray(approval.approvedFieldScope, request.fieldScope) || !sameArray(approval.approvedMediaScope, request.mediaScope) || JSON.stringify(approval.audience) !== JSON.stringify(request.audience) || approval.language !== request.language) reasons.push("PERMISSION_SCOPE_MISMATCH");
    if (approval.verificationId !== request.verificationId || approval.verificationRevision !== request.verificationVersion) reasons.push("VERIFICATION_STALE"); if (approval.permissionId !== request.permissionId || approval.permissionRevision !== request.permissionVersion) reasons.push("PERMISSION_SCOPE_MISMATCH"); if (approval.targetPolicyVersion !== request.targetPolicyVersion) reasons.push("TARGET_POLICY_CHANGED"); if (approval.channelPolicyVersion !== request.channelPolicyVersion) reasons.push("CHANNEL_POLICY_CHANGED"); if (request.actor.principalId === approval.decisionActorId) reasons.push("APPROVAL_CONFLICT");
    try { const representation = this.#exactRepresentation(approval.representationId, approval.representationVersion, approval.representationChecksum, approval.teamId); this.#dependencies(representation, approval.verificationId, approval.verificationRevision, approval.permissionId, approval.permissionRevision); } catch (error) { reasons.push(this.#code(error)); }
    const decision = immutable<EffectiveApprovalDecision>({ effective: reasons.length === 0, approvalId: approval.id, approvalVersion: approval.version, checkedAt: this.#clock().toISOString(), effectiveScope: { targetId: approval.targetId, channelId: approval.channelId, fieldScope: approval.approvedFieldScope, mediaScope: approval.approvedMediaScope, audience: approval.audience, language: approval.language }, expiresAt: approval.expiresAt, reasonCodes: [...new Set(reasons.length === 0 ? ["APPROVAL_EFFECTIVE"] : reasons)] }); this.#auditEvent("PUBLICATION_APPROVAL_EFFECTIVE_CHECKED", "publication.approval.check-effective", "PublicationApproval", approval.id, approval.version, request, approval.classification, decision.effective ? "Exact Approval binding is effective" : "Exact Approval binding is not effective", { consumerDuty: request.consumerDuty, effective: decision.effective, approvalVersion: request.approvalVersion, representationVersion: request.representationVersion, representationChecksum: request.representationChecksum, targetId: request.targetId, channelId: request.channelId, reasonCodes: decision.reasonCodes, rawContactIncluded: false, externalEffect: false }); return decision;
  }

  #validateRepresentationMaterial(request: RepresentationMaterial): void { if (request.subjectRef.entityId.trim().length === 0 || request.subjectRef.version < 1 || request.fieldScope.length === 0 || request.language.trim().length === 0 || request.provenanceRef.entityId.trim().length === 0 || request.provenanceRef.version < 1 || request.creatorId.trim().length === 0 || !publicContentIsSafe(request.canonicalContent)) throw new Error("PUBLICATION_NOT_ELIGIBLE"); this.#targetPolicy(request); }
  #authoritativeRepresentationSource(teamId: string, request: RepresentationMaterial): RepresentationSourceSnapshot { const source = this.#representationSourceResolver(teamId, request.subjectRef, request.provenanceRef); if (source?.privacyValidated !== true || source.teamId !== teamId || !sameRef(source.subjectRef, request.subjectRef) || !sameRef(source.provenanceRef, request.provenanceRef) || JSON.stringify(canonical(source.canonicalContent)) !== JSON.stringify(canonical(request.canonicalContent)) || !sameArray(source.fieldScope, request.fieldScope) || !sameArray(source.mediaScope, request.mediaScope) || source.creatorId !== request.creatorId || !sameArray(source.editorIds, request.editorIds) || (request.sourceClassification !== undefined && request.sourceClassification !== source.classification)) throw new Error("PUBLICATION_NOT_ELIGIBLE"); return source; }
  #targetPolicy(representation: RepresentationMaterial): PublicationTargetPolicySnapshot { const policy = this.#targetPolicyResolver(representation.targetId, representation.channelId); if (policy?.targetStatus !== "ACTIVE") throw new Error("TARGET_NOT_ALLOWED"); if (policy.channelStatus !== "ACTIVE") throw new Error("CHANNEL_NOT_ALLOWED"); if (policy.targetPolicyVersion !== representation.targetPolicyVersion) throw new Error("TARGET_POLICY_CHANGED"); if (policy.channelPolicyVersion !== representation.channelPolicyVersion) throw new Error("CHANNEL_POLICY_CHANGED"); if (!policy.allowedLanguages.includes(representation.language) || !policy.allowedAudienceCodes.includes(representation.audience.code) || representation.fieldScope.some((field) => !policy.allowedFields.includes(field)) || representation.mediaScope.some((media) => !policy.allowedMedia.includes(media))) throw new Error("PUBLICATION_NOT_ELIGIBLE"); return policy; }
  #verification(representation: ImmutableRepresentationSnapshot, id: string, version: number): Verification { const item = this.#verificationResolver(id); if (item === undefined) throw new Error("VERIFICATION_REQUIRED"); if (item.teamId !== representation.teamId || item.version !== version || !sameRef(item.subjectRef, representation.subjectRef)) throw new Error("VERIFICATION_STALE"); if (item.status !== "VERIFIED" || item.result !== "VERIFIED") throw new Error(item.status === "EXPIRED" || item.status === "REVOKED" ? "VERIFICATION_STALE" : "VERIFICATION_REQUIRED"); if (representation.fieldScope.some((field) => !item.fields.includes(field) || !item.fieldResults.some((result) => result.field === field && this.#clock().getTime() < new Date(result.validUntil).getTime()))) throw new Error("VERIFICATION_STALE"); return item; }
  #permission(representation: ImmutableRepresentationSnapshot, id: string, version: number, verificationId: string, verificationVersion: number): Permission { const item = this.#permissionResolver(id); if (item?.status !== "ACTIVE") throw new Error(item?.status === "EXPIRED" ? "PERMISSION_EXPIRED" : "PERMISSION_REQUIRED"); if (item.teamId !== representation.teamId || item.version !== version || item.verificationId !== verificationId || item.verificationVersion !== verificationVersion || !sameRef(item.subjectRef, representation.subjectRef)) throw new Error("PERMISSION_SCOPE_MISMATCH"); if (this.#clock().getTime() >= new Date(item.validUntil).getTime()) throw new Error("PERMISSION_EXPIRED"); if (item.permissionType !== "PUBLIC_PUBLICATION" || item.permissionPurpose !== "PURPOSE_PUBLICATION_APPROVAL" || item.audience.code !== "AUD_PUBLIC" || JSON.stringify(item.audience) !== JSON.stringify(representation.audience) || representation.fieldScope.some((field) => !item.fieldScope.includes(field))) throw new Error("PERMISSION_SCOPE_MISMATCH"); return item; }
  #dependencies(representation: ImmutableRepresentationSnapshot, verificationId: string, verificationVersion: number, permissionId: string, permissionVersion: number): DependencyResult { const verification = this.#verification(representation, verificationId, verificationVersion); const permission = this.#permission(representation, permissionId, permissionVersion, verificationId, verificationVersion); const policy = this.#targetPolicy(representation); const expiry = Math.min(new Date(permission.validUntil).getTime(), ...representation.fieldScope.map((field) => new Date(verification.fieldResults.find((result) => result.field === field)!.validUntil).getTime())); return { verification, permission, policy, expiresAt: new Date(expiry).toISOString() }; }
  #representation(id: string, version: number): ImmutableRepresentationSnapshot { const item = (this.#representationHistory.get(id) ?? []).find((candidate) => candidate.version === version); if (item === undefined) throw new Error("NOT_FOUND"); return item; }
  #exactRepresentation(id: string, version: number, checksum: string, teamId: string): ImmutableRepresentationSnapshot { const item = this.#representation(id, version); if (item.teamId !== teamId) throw new Error("NOT_FOUND"); if (item.checksum !== checksum) throw new Error("REPRESENTATION_CHECKSUM_MISMATCH"); if (this.#representations.get(id)?.version !== version) throw new Error("REPRESENTATION_CHANGED"); return item; }
  #conflicts(actorId: string, approval: PublicationApproval): readonly string[] { const representation = this.#representation(approval.representationId, approval.representationVersion); const verification = this.#verificationResolver(approval.verificationId); const permission = this.#permissionResolver(approval.permissionId); const actors = new Set([approval.requesterActorId, representation.creatorId, ...representation.editorIds, verification?.approvalHistory.findLast((entry) => entry.decision === "VERIFIED")?.actorId, permission?.approvalHistory.findLast((entry) => entry.decision === "GRANTED")?.actorId].filter((item): item is string => item !== undefined)); return actors.has(actorId) ? Object.freeze(["APPROVAL_CONFLICT"]) : Object.freeze([]); }
  #assertNoConflict(actorId: string, approval: PublicationApproval, context: Context): void { if (this.#conflicts(actorId, approval).length > 0) { this.#deny(approval, context, "APPROVAL_CONFLICT"); throw new Error("APPROVAL_CONFLICT"); } }
  #assertEligible(actor: SessionContext, approval: PublicationApproval, context: Context): void { if (actor.principalType !== "HUMAN" || !actor.roles.includes("PUA") || !this.#puaEligibilityResolver(actor.principalId, approval.teamId, "PURPOSE_PUBLICATION_APPROVAL")) { this.#deny(approval, context, "APPROVER_NOT_ELIGIBLE"); throw new Error("APPROVER_NOT_ELIGIBLE"); } }
  #assertEligibleActorId(actorId: string, approval: PublicationApproval, context: Context): void { if (!this.#puaEligibilityResolver(actorId, approval.teamId, context.purpose)) { this.#deny(approval, context, "APPROVER_NOT_ELIGIBLE"); throw new Error("APPROVER_NOT_ELIGIBLE"); } }
  #team(actor: SessionContext): string { if (actor.teamId === undefined) throw new Error("TEAM_SCOPE_REQUIRED"); return actor.teamId; }
  #scopedApproval(context: Context, id: string): PublicationApproval { const item = this.#approvals.get(id); if (item === undefined || item.teamId !== context.actor.teamId || context.purpose !== "PURPOSE_PUBLICATION_APPROVAL") throw new Error("NOT_FOUND"); return item; }
  #version(item: PublicationApproval, expected: number): void { if (item.version !== expected) throw new Error("EXPECTED_VERSION_MISMATCH"); }
  #reason(value: string): void { if (value.trim().length === 0) throw new Error("REASON_REQUIRED"); if (/(?:[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}|\+?\d[\d\s().-]{6,}\d)/iu.test(value)) throw new Error("PUBLICATION_NOT_ELIGIBLE"); }
  #authorize(context: Context, action: string, type: string, id: string, teamId: string, version?: number, reason?: string): void { const decision = this.#authorization.evaluate({ session: context.actor, action, resource: { type, id, teamId, ...(version === undefined ? {} : { version }) }, purpose: context.purpose, ...(reason === undefined ? {} : { reason }), ...(context.requestId === undefined ? {} : { requestId: context.requestId }), correlationId: context.correlationId }); if (decision.effect === "DENY") throw new Error(decision.reasonCode === "REAUTHENTICATION_REQUIRED" ? "MFA_REQUIRED" : decision.reasonCode); }
  #authorizeApproval(context: Context, action: string, approval: PublicationApproval, reason?: string): void { try { this.#authorize(context, action, "PublicationApproval", approval.id, approval.teamId, approval.version, reason); } catch (error) { const code = this.#code(error); this.#deny(approval, context, code); throw error; } }
  #replaceApproval(current: PublicationApproval, context: Context, changes: Readonly<Partial<PublicationApproval>>, eventType: string, action: string, reason: string, details: Readonly<Record<string, unknown>> = {}): PublicationApproval { const status = changes.status ?? current.status; const occurredAt = this.#clock().toISOString(); const statusHistory = status === current.status ? current.statusHistory : [...current.statusHistory, { status, actorId: context.actor.principalId, reason, occurredAt }]; const updated = immutable<PublicationApproval>({ ...current, ...changes, version: current.version + 1, statusHistory }); this.#storeApproval(updated); this.#auditEvent(eventType, action, "PublicationApproval", updated.id, updated.version, context, updated.classification, reason, { ...details, status: updated.status, representationId: updated.representationId, rawContactIncluded: false, externalEffect: false }); return updated; }
  #storeApproval(item: PublicationApproval): void { this.#approvals.set(item.id, item); this.#approvalHistory.set(item.id, [...(this.#approvalHistory.get(item.id) ?? []), item]); }
  #idempotencyKey(context: Context & { readonly idempotencyKey: string }): string { if (context.idempotencyKey.trim().length === 0) throw new Error("IDEMPOTENCY_KEY_REQUIRED"); return `${context.actor.principalId}:${context.idempotencyKey}`; }
  #replayRepresentation(context: Context & { readonly idempotencyKey: string }, fingerprint: string): ImmutableRepresentationSnapshot | undefined { const prior = this.#idempotency.get(this.#idempotencyKey(context)); if (prior === undefined) return undefined; if (prior.fingerprint !== fingerprint || prior.kind !== "REPRESENTATION") throw new Error("IDEMPOTENCY_CONFLICT"); return this.#representation(prior.id, prior.version); }
  #replayApproval(context: Context & { readonly idempotencyKey: string }, fingerprint: string, revalidatePrerequisites = true, reauthorize?: (approval: PublicationApproval) => void): PublicationApproval | undefined { const prior = this.#idempotency.get(this.#idempotencyKey(context)); if (prior === undefined) return undefined; if (prior.fingerprint !== fingerprint || prior.kind !== "APPROVAL") throw new Error("IDEMPOTENCY_CONFLICT"); const approval = (this.#approvalHistory.get(prior.id) ?? []).find((item) => item.version === prior.version); if (approval === undefined) throw new Error("NOT_FOUND"); reauthorize?.(approval); if (revalidatePrerequisites) { const representation = this.#exactRepresentation(approval.representationId, approval.representationVersion, approval.representationChecksum, approval.teamId); this.#dependencies(representation, approval.verificationId, approval.verificationRevision, approval.permissionId, approval.permissionRevision); } this.#auditEvent("PUBLICATION_APPROVAL_REPLAY_AUTHORIZED", "publication.approval.replay", "PublicationApproval", approval.id, approval.version, context, approval.classification, "Idempotent replay reauthorized against current prerequisites", { idempotencyOutcome: "REPLAYED", prerequisiteRecheck: revalidatePrerequisites ? "PASSED" : "NOT_APPLICABLE_TERMINAL_OPERATION", rawContactIncluded: false, externalEffect: false }); return approval; }
  #remember(context: Context & { readonly idempotencyKey: string }, fingerprint: string, kind: IdempotencyRecord["kind"], id: string, version: number): void { this.#idempotency.set(this.#idempotencyKey(context), Object.freeze({ fingerprint, kind, id, version })); }
  #deny(approval: PublicationApproval, context: Context, reason: string): void { this.#auditEvent("PUBLICATION_APPROVAL_DENIED", "publication.approval.authorize", "PublicationApproval", approval.id, approval.version, context, approval.classification, reason, { reasonCode: reason, rawContactIncluded: false, stateChanged: false }); }
  #auditEvent(eventType: string, action: string, type: string, id: string, version: number, context: Context, classification: DataClassification, reason: string, details: Readonly<Record<string, unknown>>): void { this.#audit.append({ eventType, principal: principal(context.actor), action, target: { type, id, version }, purpose: context.purpose, policyVersion: this.#policyVersion, classification, decision: eventType.endsWith("DENIED") ? "DENY" : "ALLOW", outcome: eventType.endsWith("DENIED") ? "FAILED" : "COMPLETED", reason, ...(context.requestId === undefined ? {} : { requestId: context.requestId }), correlationId: context.correlationId, details }); }
  #code(error: unknown): string { return error instanceof Error ? error.message : "APPROVAL_NOT_EFFECTIVE"; }
}
