import type { AuditPrincipal, AuditSink, Clock, IdFactory } from "../../../packages/security-contracts/src/index.js";
import type { AuthorizationService } from "../../authorization/src/authorization-service.js";
import { validateAdvisoryResult, type AdvisoryValidationDecision } from "../../ai/src/advisory-ai-service.js";
import type { SessionContext } from "../../identity/src/session-service.js";

export interface DomainReference { readonly entityType: string; readonly entityId: string; readonly version: number }
export interface Client { readonly id: string; readonly version: number; readonly status: "ACTIVE" | "DORMANT" | "CLOSED"; readonly teamId: string; readonly assignedAgentId: string; readonly contactRef: DomainReference; readonly consentRefs: readonly string[]; readonly classification: "RESTRICTED_PERSONAL" }
export interface RequirementConstraint { readonly criterion: string; readonly kind: "HARD" | "SOFT" | "EXCLUDE" | "UNKNOWN"; readonly value: string }
export interface Budget { readonly currency: string; readonly lower?: number; readonly upper?: number; readonly frequency: string }
export interface LocationPreference { readonly rawTerm: string; readonly canonicalLocationId?: string; readonly preference: "DESIRED" | "AVOID" | "FLEXIBLE" }
export type RequirementStatus = "DRAFT" | "ACTIVE" | "PAUSED" | "FULFILLED" | "WITHDRAWN" | "EXPIRED";
export interface Requirement { readonly id: string; readonly version: number; readonly clientId: string; readonly teamId: string; readonly status: RequirementStatus; readonly intent: "RENT" | "BUY" | "OTHER" | "UNKNOWN"; readonly constraints: readonly RequirementConstraint[]; readonly budget: Budget | undefined; readonly locations: readonly LocationPreference[]; readonly originalSourceRef: DomainReference; readonly validationGaps: readonly string[]; readonly readiness: "READY" | "NOT_READY"; readonly staleMatchSignal: boolean; readonly classification: "RESTRICTED_PERSONAL"; readonly changedBy: string; readonly changedAt: string; readonly changeReason: string }

interface Dependencies { readonly authorizationService: AuthorizationService; readonly auditSink: AuditSink; readonly clock: Clock; readonly idFactory: IdFactory; readonly policyVersion: string }
interface Context { readonly actor: SessionContext; readonly purpose: string; readonly correlationId: string; readonly requestId?: string }
type RequirementFields = Pick<Requirement, "intent" | "constraints" | "locations" | "validationGaps"> & { readonly budget?: Budget };

function deepFreeze(value: unknown): void { if (value !== null && typeof value === "object" && !Object.isFrozen(value)) { Object.values(value).forEach(deepFreeze); Object.freeze(value); } }
function immutable<T>(value: T): T { const copy = structuredClone(value); deepFreeze(copy); return copy; }
function principal(session: SessionContext): AuditPrincipal { return { id: session.principalId, type: session.principalType, roles: session.roles, ...(session.teamId === undefined ? {} : { teamId: session.teamId }), sessionId: session.id }; }

export class ClientRequirementService {
  readonly #authorization: AuthorizationService; readonly #audit: AuditSink; readonly #clock: Clock; readonly #idFactory: IdFactory; readonly #policyVersion: string; readonly #clients = new Map<string, Client>(); readonly #requirements = new Map<string, Requirement>(); readonly #history = new Map<string, Requirement[]>();
  public constructor(dependencies: Dependencies) { this.#authorization = dependencies.authorizationService; this.#audit = dependencies.auditSink; this.#clock = dependencies.clock; this.#idFactory = dependencies.idFactory; this.#policyVersion = dependencies.policyVersion; }

  public createClient(request: Context & { readonly teamId: string; readonly assignedAgentId: string; readonly contactRef: DomainReference; readonly consentRefs: readonly string[] }): Client {
    if (request.contactRef.entityType !== "Contact" || request.contactRef.version < 1 || request.consentRefs.length === 0) throw new Error("CONSENT_SCOPE_DENIED"); if (request.actor.principalId !== request.assignedAgentId && !request.actor.roles.includes("SAG")) throw new Error("CLIENT_SCOPE_DENIED"); this.#authorize(request, "client.create", "Client", "new", request.teamId);
    const client = immutable({ id: this.#idFactory(), version: 1, status: "ACTIVE" as const, teamId: request.teamId, assignedAgentId: request.assignedAgentId, contactRef: request.contactRef, consentRefs: request.consentRefs, classification: "RESTRICTED_PERSONAL" as const }); this.#clients.set(client.id, client); this.#record("CLIENT_CREATED", "client.create", "Client", client.id, client.version, request, client.teamId); return client;
  }

  public readClient(request: Context & { readonly clientId: string }): Client { const client = this.#client(request.clientId); this.#authorize(request, "client.read", "Client", client.id, client.teamId, client.version, undefined, "CLIENT_SCOPE_DENIED"); return client; }

  public createRequirement(request: Context & { readonly clientId: string; readonly expectedClientVersion: number; readonly originalSourceRef: DomainReference } & RequirementFields): Requirement {
    const client = this.#client(request.clientId); this.#version(client.version, request.expectedClientVersion); if (request.originalSourceRef.version < 1) throw new Error("PROVENANCE_REQUIRED"); this.#assigned(request, client); this.#authorize(request, "requirement.create", "Requirement", "new", client.teamId);
    const requirement = immutable({ id: this.#idFactory(), version: 1, clientId: client.id, teamId: client.teamId, status: "DRAFT" as const, intent: request.intent, constraints: request.constraints, budget: request.budget, locations: request.locations, originalSourceRef: request.originalSourceRef, validationGaps: this.#gaps(request), readiness: "NOT_READY" as const, staleMatchSignal: false, classification: "RESTRICTED_PERSONAL" as const, changedBy: request.actor.principalId, changedAt: this.#clock().toISOString(), changeReason: "INITIAL_DRAFT" }); this.#requirements.set(requirement.id, requirement); this.#append(requirement); this.#record("REQUIREMENT_DRAFT_CREATED", "requirement.create", "Requirement", requirement.id, requirement.version, request, client.teamId); return requirement;
  }

  public activateRequirement(request: Context & { readonly requirementId: string; readonly expectedVersion: number; readonly reason: string }): Requirement {
    const current = this.#requirement(request.requirementId); const client = this.#client(current.clientId); this.#version(current.version, request.expectedVersion); this.#reason(request.reason); if (current.status !== "DRAFT" || current.validationGaps.length > 0 || current.intent === "UNKNOWN") throw new Error("REQUIREMENT_INVALID"); this.#assigned(request, client); this.#authorize(request, "requirement.activate", "Requirement", current.id, current.teamId, current.version);
    return this.#replace(current, request, { status: "ACTIVE", readiness: "READY", staleMatchSignal: current.staleMatchSignal }, "REQUIREMENT_ACTIVATED", "requirement.activate");
  }

  public reviseRequirement(request: Context & { readonly requirementId: string; readonly expectedVersion: number; readonly reason: string; readonly material: boolean } & RequirementFields): Requirement {
    const current = this.#requirement(request.requirementId); const client = this.#client(current.clientId); this.#version(current.version, request.expectedVersion); this.#reason(request.reason); this.#assigned(request, client); this.#authorize(request, "requirement.revise", "Requirement", current.id, current.teamId, current.version);
    const gaps = this.#gaps(request); return this.#replace(current, request, { status: "DRAFT", intent: request.intent, constraints: request.constraints, budget: request.budget, locations: request.locations, validationGaps: gaps, readiness: "NOT_READY", staleMatchSignal: current.staleMatchSignal || request.material }, "REQUIREMENT_REVISED", "requirement.revise");
  }

  public transitionRequirement(request: Context & { readonly requirementId: string; readonly expectedVersion: number; readonly targetStatus: "ACTIVE" | "PAUSED" | "FULFILLED" | "WITHDRAWN" | "EXPIRED"; readonly reason: string }): Requirement {
    const current = this.#requirement(request.requirementId); const client = this.#client(current.clientId); this.#version(current.version, request.expectedVersion); this.#reason(request.reason); this.#assigned(request, client); this.#authorize(request, "requirement.transition", "Requirement", current.id, current.teamId, current.version); const valid = current.status === "ACTIVE" ? request.targetStatus !== "ACTIVE" : current.status === "PAUSED" && (request.targetStatus === "ACTIVE" || request.targetStatus === "WITHDRAWN"); if (!valid) throw new Error("STATE_TRANSITION_INVALID"); if (request.targetStatus === "ACTIVE" && (current.validationGaps.length > 0 || current.intent === "UNKNOWN")) throw new Error("REQUIREMENT_INVALID");
    return this.#replace(current, request, { status: request.targetStatus, readiness: request.targetStatus === "ACTIVE" ? "READY" : "NOT_READY" }, "REQUIREMENT_TRANSITIONED", "requirement.transition");
  }

  public readRequirement(request: Context & { readonly requirementId: string }): Requirement { const current = this.#requirement(request.requirementId); this.#authorize(request, "requirement.read", "Requirement", current.id, current.teamId, current.version); return current; }
  public readRequirementHistory(request: Context & { readonly requirementId: string }): readonly Requirement[] { const current = this.#requirement(request.requirementId); this.#authorize(request, "requirement.read", "Requirement", current.id, current.teamId, current.version); return Object.freeze([...(this.#history.get(current.id) ?? [])]); }
  public validateRequirementProposal(request: Context & { readonly requirementId: string; readonly expectedVersion: number; readonly result: unknown }): AdvisoryValidationDecision { return this.#validateAdvisory(request, "AI-004"); }
  public validateSearchInterpretation(request: Context & { readonly requirementId: string; readonly expectedVersion: number; readonly result: unknown }): AdvisoryValidationDecision { return this.#validateAdvisory(request, "AI-006"); }

  #client(id: string): Client { const item = this.#clients.get(id); if (item === undefined) throw new Error("CLIENT_NOT_FOUND"); return item; }
  #requirement(id: string): Requirement { const item = this.#requirements.get(id); if (item === undefined) throw new Error("CLIENT_NOT_FOUND"); return item; }
  #version(actual: number, expected: number): void { if (actual !== expected) throw new Error("VERSION_CONFLICT"); }
  #reason(reason: string): void { if (reason.trim().length === 0) throw new Error("REASON_REQUIRED"); }
  #assigned(context: Context, client: Client): void { if (context.actor.principalType === "HUMAN" && context.actor.principalId !== client.assignedAgentId && !context.actor.roles.includes("SAG")) throw new Error("CLIENT_SCOPE_DENIED"); }
  #gaps(fields: RequirementFields): readonly string[] { const gaps = [...fields.validationGaps]; if (fields.intent === "UNKNOWN") gaps.push("intent"); if (fields.budget?.lower !== undefined && fields.budget.upper !== undefined && fields.budget.lower > fields.budget.upper) gaps.push("budget-range"); return Object.freeze([...new Set(gaps)]); }
  #append(requirement: Requirement): void { this.#history.set(requirement.id, [...(this.#history.get(requirement.id) ?? []), requirement]); }
  #validateAdvisory(request: Context & { readonly requirementId: string; readonly expectedVersion: number; readonly result: unknown }, capabilityId: "AI-004" | "AI-006"): AdvisoryValidationDecision { const current = this.#requirement(request.requirementId); this.#version(current.version, request.expectedVersion); this.#authorize(request, "requirement.request-ai", "Requirement", current.id, current.teamId, current.version); const decision = validateAdvisoryResult({ expectedCapabilityId: capabilityId, expectedSubject: { entityType: "Requirement", entityId: current.id, version: current.version }, inputClassifications: [current.classification], result: request.result }); this.#audit.append({ eventType: "REQUIREMENT_AI_RESULT_VALIDATED", principal: principal(request.actor), action: "requirement.request-ai", target: { type: "Requirement", id: current.id, version: current.version }, purpose: request.purpose, policyVersion: this.#policyVersion, classification: current.classification, decision: "NOT_APPLICABLE", outcome: decision.status === "VALID" ? "COMPLETED" : "FAILED", ...(request.requestId === undefined ? {} : { requestId: request.requestId }), correlationId: request.correlationId, details: { capabilityId, validationStatus: decision.status, reviewRoute: decision.route, ...(decision.reasonCode === undefined ? {} : { reasonCode: decision.reasonCode }), authority: "ADVISORY" } }); return decision; }
  #replace(current: Requirement, context: Context & { readonly reason: string }, changes: Readonly<Partial<Requirement>>, eventType: string, action: string): Requirement { const updated = immutable({ ...current, ...changes, version: current.version + 1, changedBy: context.actor.principalId, changedAt: this.#clock().toISOString(), changeReason: context.reason }); this.#requirements.set(updated.id, updated); this.#append(updated); this.#record(eventType, action, "Requirement", updated.id, updated.version, context, updated.teamId); return updated; }
  #authorize(context: Context, action: string, type: string, id: string, teamId: string, version?: number, reason?: string, deniedCode = "SCOPE_DENIED"): void { if (context.actor.teamId !== teamId) throw new Error(deniedCode); const decision = this.#authorization.evaluate({ session: context.actor, action, resource: { type, id, teamId, ...(version === undefined ? {} : { version }) }, purpose: context.purpose, ...(reason === undefined ? {} : { reason }), ...(context.requestId === undefined ? {} : { requestId: context.requestId }), correlationId: context.correlationId }); if (decision.effect === "DENY") throw new Error(decision.reasonCode); }
  #record(eventType: string, action: string, type: string, id: string, version: number, context: Context, teamId: string): void { this.#audit.append({ eventType, principal: principal(context.actor), action, target: { type, id, version }, purpose: context.purpose, policyVersion: this.#policyVersion, classification: "RESTRICTED_PERSONAL", decision: "ALLOW", outcome: "COMPLETED", ...(context.requestId === undefined ? {} : { requestId: context.requestId }), correlationId: context.correlationId, details: { teamId, provenancePreserved: true, rawContentLogged: false } }); }
}
