import type { AuditPrincipal, AuditSink, Clock, DataClassification, IdFactory } from "../../../packages/security-contracts/src/index.js";
import { validateAdvisoryResult, type AdvisoryValidationDecision } from "../../ai/src/advisory-ai-service.js";
import type { AuthorizationService } from "../../authorization/src/authorization-service.js";
import type { SessionContext } from "../../identity/src/session-service.js";

export type VerificationField = "AVAILABILITY" | "PRICE" | "CONTACT_REACHABILITY" | "LEGAL_DOCUMENTS";
export type VerificationStatus = "REQUESTED" | "IN_REVIEW" | "VERIFIED" | "EXPIRING" | "EXPIRED" | "REJECTED" | "INSUFFICIENT" | "REVOKED";
export type VerificationDecision = "VERIFIED" | "REJECTED" | "INSUFFICIENT";
export type ReverificationTrigger = "PRICE_CHANGE" | "AVAILABILITY_CHANGE" | "LISTING_REVISION" | "CONTACT_CHANGE" | "WITHDRAWAL" | "EXPIRATION";
export interface VersionedEntityReference { readonly entityType: string; readonly entityId: string; readonly version: number }
export interface VerificationEvidenceReference extends VersionedEntityReference { readonly classification: DataClassification }
export interface VerificationFieldResult { readonly field: VerificationField; readonly result: "VERIFIED"; readonly validFrom: string; readonly validUntil: string }
export interface VerificationReviewEntry { readonly actorId: string; readonly action: "REQUEST_EVIDENCE" | "RECOMMEND" | "ESCALATE"; readonly recommendation: string; readonly occurredAt: string }
export interface ApprovalHistory { readonly actorId: string; readonly decision: VerificationDecision | "REVOKED"; readonly reason: string; readonly occurredAt: string; readonly managerOverride: boolean }
export interface StatusHistory { readonly status: VerificationStatus; readonly actorId: string; readonly occurredAt: string; readonly reason: string }
export interface Verification { readonly id: string; readonly version: number; readonly teamId: string; readonly subjectRef: VersionedEntityReference; readonly matchResultRef?: VersionedEntityReference; readonly priorVerificationId?: string; readonly fields: readonly VerificationField[]; readonly evidenceReferences: readonly VerificationEvidenceReference[]; readonly status: VerificationStatus; readonly result?: VerificationDecision | "REVOKED"; readonly assignmentId?: string; readonly createdBy: string; readonly requestedAt: string; readonly fieldResults: readonly VerificationFieldResult[]; readonly reviewHistory: readonly VerificationReviewEntry[]; readonly approvalHistory: readonly ApprovalHistory[]; readonly statusHistory: readonly StatusHistory[]; readonly classification: DataClassification; readonly policyVersion: string }
export interface Availability { readonly id: string; readonly version: 1; readonly offerRef: VersionedEntityReference; readonly verificationId: string; readonly status: "AVAILABLE" | "EXPIRED" | "REVOKED"; readonly asOf: string; readonly expiresAt: string; readonly classification: "CONFIDENTIAL_BUSINESS" }
export interface VerifierAssignment { readonly id: string; readonly version: 1; readonly verificationId: string; readonly principalId: string; readonly role: "VER" | "MGR" | "REV"; readonly qualificationReference: string; readonly effectiveFrom: string; readonly effectiveUntil: string; readonly assignedBy: string; readonly status: "ACTIVE" }
export interface ReverificationRequest { readonly id: string; readonly version: 1; readonly priorVerificationId: string; readonly successorVerificationId: string; readonly trigger: ReverificationTrigger; readonly dueAt: string; readonly status: "SCHEDULED"; readonly requestedBy: string }

interface Dependencies { readonly authorizationService: AuthorizationService; readonly auditSink: AuditSink; readonly clock: Clock; readonly idFactory: IdFactory; readonly policyVersion: string }
interface Context { readonly actor: SessionContext; readonly purpose: string; readonly correlationId: string; readonly requestId?: string }
interface IdempotencyRecord { readonly fingerprint: string; readonly verificationId: string }
interface ReverificationIdempotencyRecord { readonly fingerprint: string; readonly result: Readonly<{ readonly verification: Verification; readonly request: ReverificationRequest }> }
const validityDays: Readonly<Record<VerificationField, number>> = Object.freeze({ AVAILABILITY: 7, PRICE: 14, CONTACT_REACHABILITY: 30, LEGAL_DOCUMENTS: 90 });
const terminalForReverification = new Set<VerificationStatus>(["EXPIRING", "EXPIRED", "REJECTED", "INSUFFICIENT", "REVOKED"]);
function deepFreeze(value: unknown): void { if (value !== null && typeof value === "object" && !Object.isFrozen(value)) { Object.values(value).forEach(deepFreeze); Object.freeze(value); } }
function immutable<T>(value: T): T { const snapshot = structuredClone(value); deepFreeze(snapshot); return snapshot; }
function principal(actor: SessionContext): AuditPrincipal { return { id: actor.principalId, type: actor.principalType, roles: actor.roles, ...(actor.teamId === undefined ? {} : { teamId: actor.teamId }), sessionId: actor.id }; }
function addDays(value: Date, days: number): string { return new Date(value.getTime() + days * 86_400_000).toISOString(); }

export class VerificationService {
  readonly #authorization: AuthorizationService; readonly #audit: AuditSink; readonly #clock: Clock; readonly #idFactory: IdFactory; readonly #policyVersion: string;
  readonly #verifications = new Map<string, Verification>(); readonly #history = new Map<string, Verification[]>(); readonly #assignments = new Map<string, VerifierAssignment>(); readonly #availability = new Map<string, Availability>(); readonly #reverificationRequests = new Map<string, ReverificationRequest>(); readonly #idempotency = new Map<string, IdempotencyRecord>(); readonly #reverificationIdempotency = new Map<string, ReverificationIdempotencyRecord>();
  public constructor(dependencies: Dependencies) { this.#authorization = dependencies.authorizationService; this.#audit = dependencies.auditSink; this.#clock = dependencies.clock; this.#idFactory = dependencies.idFactory; this.#policyVersion = dependencies.policyVersion; }

  public requestVerification(request: Context & { readonly subjectRef: VersionedEntityReference; readonly matchResultRef?: VersionedEntityReference; readonly fields: readonly VerificationField[]; readonly evidenceReferences: readonly VerificationEvidenceReference[]; readonly reason: string; readonly idempotencyKey: string }): Verification {
    this.#validateRequest(request); const teamId = this.#team(request.actor); this.#authorize(request, "verification.request", "Verification", "new", teamId, undefined, request.reason);
    const fingerprint = JSON.stringify({ subjectRef: request.subjectRef, matchResultRef: request.matchResultRef, fields: [...request.fields].sort(), evidenceReferences: request.evidenceReferences, purpose: request.purpose }); const key = `${request.actor.principalId}:${request.idempotencyKey}`; const prior = this.#idempotency.get(key);
    if (prior !== undefined) { if (prior.fingerprint !== fingerprint) throw new Error("IDEMPOTENCY_CONFLICT"); return this.#current(prior.verificationId); }
    const occurredAt = this.#clock().toISOString(); const verification = immutable<Verification>({ id: this.#idFactory(), version: 1, teamId, subjectRef: request.subjectRef, ...(request.matchResultRef === undefined ? {} : { matchResultRef: request.matchResultRef }), fields: [...new Set(request.fields)], evidenceReferences: request.evidenceReferences, status: "REQUESTED", createdBy: request.actor.principalId, requestedAt: occurredAt, fieldResults: [], reviewHistory: [], approvalHistory: [], statusHistory: [{ status: "REQUESTED", actorId: request.actor.principalId, occurredAt, reason: request.reason }], classification: this.#classification(request.evidenceReferences), policyVersion: this.#policyVersion });
    this.#store(verification); this.#idempotency.set(key, Object.freeze({ fingerprint, verificationId: verification.id })); this.#record("VERIFICATION_REQUESTED", "verification.request", verification, request, { fieldScope: verification.fields, evidenceReferenceCount: verification.evidenceReferences.length, matchContextIncluded: verification.matchResultRef !== undefined }); return verification;
  }

  public assignVerifier(request: Context & { readonly verificationId: string; readonly expectedVersion: number; readonly assigneePrincipalId: string; readonly assigneeRole: VerifierAssignment["role"]; readonly qualificationReference: string; readonly effectiveUntil: string; readonly reason: string }): Readonly<{ readonly verification: Verification; readonly assignment: VerifierAssignment }> {
    const current = this.#scopedCurrent(request, request.verificationId); this.#version(current, request.expectedVersion); this.#reason(request.reason); if (current.status !== "REQUESTED" || request.qualificationReference.trim().length === 0 || new Date(request.effectiveUntil).getTime() <= this.#clock().getTime()) throw new Error("VERIFIER_ASSIGNMENT_INVALID"); this.#authorize(request, "verification.assign", "VerifierAssignment", "new", current.teamId, undefined, request.reason);
    const assignment = immutable<VerifierAssignment>({ id: this.#idFactory(), version: 1, verificationId: current.id, principalId: request.assigneePrincipalId, role: request.assigneeRole, qualificationReference: request.qualificationReference, effectiveFrom: this.#clock().toISOString(), effectiveUntil: request.effectiveUntil, assignedBy: request.actor.principalId, status: "ACTIVE" }); this.#assignments.set(assignment.id, assignment);
    const verification = this.#replace(current, request, { status: "IN_REVIEW", assignmentId: assignment.id }, "VERIFICATION_ASSIGNED", "verification.assign", request.reason); return Object.freeze({ verification, assignment });
  }

  public recordReviewSupport(request: Context & { readonly verificationId: string; readonly expectedVersion: number; readonly action: VerificationReviewEntry["action"]; readonly recommendation: string }): Verification {
    const current = this.#scopedCurrent(request, request.verificationId); this.#version(current, request.expectedVersion); this.#reason(request.recommendation); if (current.status !== "IN_REVIEW") throw new Error("STATE_TRANSITION_INVALID"); this.#authorize(request, "verification.review", "Verification", current.id, current.teamId, current.version, request.recommendation); this.#activeAssignment(current, request.actor, "REV");
    const entry = immutable<VerificationReviewEntry>({ actorId: request.actor.principalId, action: request.action, recommendation: request.recommendation, occurredAt: this.#clock().toISOString() }); return this.#replace(current, request, { reviewHistory: [...current.reviewHistory, entry] }, "VERIFICATION_REVIEW_SUPPORTED", "verification.review", request.recommendation);
  }

  public decide(request: Context & { readonly verificationId: string; readonly expectedVersion: number; readonly decision: VerificationDecision; readonly reason: string; readonly managerOverride?: boolean }): Verification {
    const current = this.#scopedCurrent(request, request.verificationId); this.#version(current, request.expectedVersion); this.#reason(request.reason); if (current.status !== "IN_REVIEW") throw new Error("STATE_TRANSITION_INVALID"); const override = request.managerOverride === true; if (override && !request.actor.roles.includes("MGR")) throw new Error("MANAGER_OVERRIDE_DENIED"); const action = override ? "verification.override" : "verification.perform";
    this.#authorize(request, action, "Verification", current.id, current.teamId, current.version, request.reason, override ? undefined : current.createdBy); this.#activeAssignment(current, request.actor, request.actor.roles.includes("MGR") ? "MGR" : "VER");
    const occurredAt = this.#clock(); const fieldResults = request.decision === "VERIFIED" ? current.fields.map((field) => immutable<VerificationFieldResult>({ field, result: "VERIFIED", validFrom: occurredAt.toISOString(), validUntil: addDays(occurredAt, validityDays[field]) })) : []; const approval = immutable<ApprovalHistory>({ actorId: request.actor.principalId, decision: request.decision, reason: request.reason, occurredAt: occurredAt.toISOString(), managerOverride: override });
    const updated = this.#replace(current, request, { status: request.decision, result: request.decision, fieldResults, approvalHistory: [...current.approvalHistory, approval] }, "VERIFICATION_DECIDED", action, request.reason); if (updated.status === "VERIFIED" && updated.fields.includes("AVAILABILITY")) this.#createAvailability(updated); return updated;
  }

  public revoke(request: Context & { readonly verificationId: string; readonly expectedVersion: number; readonly trigger: Exclude<ReverificationTrigger, "EXPIRATION">; readonly reason: string; readonly managerOverride?: boolean }): Verification {
    const current = this.#scopedCurrent(request, request.verificationId); this.#version(current, request.expectedVersion); this.#reason(request.reason); if (current.status !== "VERIFIED" && current.status !== "EXPIRING") throw new Error("STATE_TRANSITION_INVALID"); const override = request.managerOverride === true; if (override && !request.actor.roles.includes("MGR")) throw new Error("MANAGER_OVERRIDE_DENIED"); const action = override ? "verification.override" : "verification.perform"; this.#authorize(request, action, "Verification", current.id, current.teamId, current.version, request.reason, override ? undefined : current.createdBy); if (!request.actor.roles.includes("MGR")) this.#activeAssignment(current, request.actor, "VER");
    const approval = immutable<ApprovalHistory>({ actorId: request.actor.principalId, decision: "REVOKED", reason: request.reason, occurredAt: this.#clock().toISOString(), managerOverride: override }); const updated = this.#replace(current, request, { status: "REVOKED", result: "REVOKED", approvalHistory: [...current.approvalHistory, approval] }, "VERIFICATION_REVOKED", action, `${request.trigger}:${request.reason}`); this.#restrictAvailability(updated.id, "REVOKED"); return updated;
  }

  public evaluateExpiry(request: Context & { readonly verificationId: string; readonly expectedVersion: number }): Verification {
    const current = this.#scopedCurrent(request, request.verificationId); this.#version(current, request.expectedVersion); if (request.actor.principalType !== "SERVICE" || !request.actor.roles.includes("SVC")) throw new Error("SERVICE_AUTHORITY_REQUIRED"); if (current.status !== "VERIFIED" && current.status !== "EXPIRING") throw new Error("STATE_TRANSITION_INVALID"); this.#authorize(request, "verification.expire", "Verification", current.id, current.teamId, current.version);
    const earliest = Math.min(...current.fieldResults.map((item) => new Date(item.validUntil).getTime())); const remaining = earliest - this.#clock().getTime(); if (remaining > 86_400_000) return current; const status: VerificationStatus = remaining <= 0 ? "EXPIRED" : "EXPIRING"; if (status === current.status) return current; const updated = this.#replace(current, request, { status }, status === "EXPIRED" ? "VERIFICATION_EXPIRED" : "VERIFICATION_EXPIRING", "verification.expire", status === "EXPIRED" ? "Validity ended" : "Validity ending within one day"); if (status === "EXPIRED") this.#restrictAvailability(updated.id, "EXPIRED"); return updated;
  }

  public requestReverification(request: Context & { readonly priorVerificationId: string; readonly expectedVersion: number; readonly trigger: ReverificationTrigger; readonly reason: string; readonly idempotencyKey: string }): Readonly<{ readonly verification: Verification; readonly request: ReverificationRequest }> {
    const prior = this.#scopedCurrent(request, request.priorVerificationId); this.#version(prior, request.expectedVersion); this.#reason(request.reason); if (!terminalForReverification.has(prior.status)) throw new Error("REVERIFICATION_NOT_REQUIRED");
    const key = `${request.actor.principalId}:${request.idempotencyKey}`; const fingerprint = JSON.stringify({ priorVerificationId: prior.id, expectedVersion: request.expectedVersion, trigger: request.trigger, reason: request.reason, purpose: request.purpose }); const replay = this.#reverificationIdempotency.get(key); if (replay !== undefined) { if (replay.fingerprint !== fingerprint) throw new Error("IDEMPOTENCY_CONFLICT"); return replay.result; }
    const verification = this.requestVerification({ ...request, subjectRef: prior.subjectRef, ...(prior.matchResultRef === undefined ? {} : { matchResultRef: prior.matchResultRef }), fields: prior.fields, evidenceReferences: prior.evidenceReferences }); const linked = this.#replace(verification, request, { priorVerificationId: prior.id }, "REVERIFICATION_LINKED", "verification.request", request.reason);
    const task = immutable<ReverificationRequest>({ id: this.#idFactory(), version: 1, priorVerificationId: prior.id, successorVerificationId: linked.id, trigger: request.trigger, dueAt: this.#clock().toISOString(), status: "SCHEDULED", requestedBy: request.actor.principalId }); this.#reverificationRequests.set(task.id, task); this.#record("REVERIFICATION_REQUESTED", "verification.request", linked, request, { priorVerificationId: prior.id, trigger: request.trigger, taskId: task.id }); const result = Object.freeze({ verification: linked, request: task }); this.#reverificationIdempotency.set(key, Object.freeze({ fingerprint, result })); return result;
  }

  public readVerification(request: Context & { readonly verificationId: string }): Verification { const current = this.#scopedCurrent(request, request.verificationId); this.#authorize(request, "verification.read", "Verification", current.id, current.teamId, current.version); return current; }
  public readHistory(request: Context & { readonly verificationId: string }): readonly Verification[] { const current = this.#scopedCurrent(request, request.verificationId); this.#authorize(request, "verification.read", "Verification", current.id, current.teamId, current.version); return Object.freeze([...(this.#history.get(current.id) ?? [])]); }
  public readAvailability(request: Context & { readonly verificationId: string }): Availability | undefined { const current = this.readVerification(request); return this.#availability.get(current.id); }
  public listQueue(request: Context): readonly Verification[] { const teamId = this.#team(request.actor); this.#authorize(request, "verification.read", "Verification", "collection", teamId); return Object.freeze([...this.#verifications.values()].filter((item) => item.teamId === teamId && (item.status === "REQUESTED" || item.status === "IN_REVIEW"))); }
  public listExpiry(request: Context): readonly Verification[] { const teamId = this.#team(request.actor); this.#authorize(request, "verification.read", "Verification", "expiry-collection", teamId); return Object.freeze([...this.#verifications.values()].filter((item) => item.teamId === teamId && (item.status === "EXPIRING" || item.status === "EXPIRED" || item.status === "REVOKED"))); }
  public validateEvidence(request: Context & { readonly verificationId: string; readonly expectedVersion: number; readonly result: unknown }): AdvisoryValidationDecision { const current = this.readVerification(request); this.#version(current, request.expectedVersion); const decision = validateAdvisoryResult({ expectedCapabilityId: "AI-007", expectedSubject: { entityType: "Verification", entityId: current.id, version: current.version }, inputClassifications: [current.classification], result: request.result }); this.#record("VERIFICATION_AI_EVIDENCE_VALIDATED", "verification.read", current, request, { capabilityId: "AI-007", validationStatus: decision.status, route: decision.route, authority: "ADVISORY", rawContentLogged: false }); return decision; }

  #validateRequest(request: { readonly subjectRef: VersionedEntityReference; readonly fields: readonly VerificationField[]; readonly evidenceReferences: readonly VerificationEvidenceReference[]; readonly reason: string; readonly idempotencyKey: string }): void { if (request.subjectRef.entityId.trim().length === 0 || request.subjectRef.version < 1 || request.fields.length === 0 || request.evidenceReferences.length === 0 || request.evidenceReferences.some((item) => item.entityId.trim().length === 0 || item.version < 1)) throw new Error("VERIFICATION_EVIDENCE_REQUIRED"); this.#reason(request.reason); if (request.idempotencyKey.trim().length === 0) throw new Error("IDEMPOTENCY_CONFLICT"); }
  #classification(references: readonly VerificationEvidenceReference[]): DataClassification { const rank: Readonly<Record<DataClassification, number>> = { PUBLIC_APPROVED: 0, INTERNAL: 1, CONFIDENTIAL_BUSINESS: 2, RESTRICTED_PERSONAL: 3, RESTRICTED_SECURITY: 4 }; return [...references].sort((left, right) => rank[right.classification] - rank[left.classification])[0]?.classification ?? "RESTRICTED_SECURITY"; }
  #team(actor: SessionContext): string { if (actor.teamId === undefined) throw new Error("SCOPE_DENIED"); return actor.teamId; }
  #current(id: string): Verification { const item = this.#verifications.get(id); if (item === undefined) throw new Error("VERIFICATION_NOT_FOUND"); return item; }
  #scopedCurrent(context: Context, id: string): Verification { const item = this.#current(id); if (context.actor.teamId !== item.teamId) throw new Error("VERIFICATION_NOT_FOUND"); return item; }
  #version(current: Verification, expected: number): void { if (current.version !== expected) throw new Error("VERSION_CONFLICT"); }
  #reason(reason: string): void { if (reason.trim().length === 0) throw new Error("REASON_REQUIRED"); if (/(?:[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}|\+?\d[\d\s().-]{6,}\d)/iu.test(reason)) throw new Error("SENSITIVE_FIELD_RESTRICTED"); }
  #activeAssignment(current: Verification, actor: SessionContext, requiredRole: "VER" | "MGR" | "REV"): VerifierAssignment { const assignment = current.assignmentId === undefined ? undefined : this.#assignments.get(current.assignmentId); if (assignment?.status !== "ACTIVE" || assignment.principalId !== actor.principalId || assignment.role !== requiredRole || this.#clock().getTime() >= new Date(assignment.effectiveUntil).getTime()) throw new Error("VERIFIER_ASSIGNMENT_DENIED"); return assignment; }
  #authorize(context: Context, action: string, type: string, id: string, teamId: string, version?: number, reason?: string, createdBy?: string): void { const decision = this.#authorization.evaluate({ session: context.actor, action, resource: { type, id, teamId, ...(version === undefined ? {} : { version }), ...(createdBy === undefined ? {} : { createdBy }) }, purpose: context.purpose, ...(reason === undefined ? {} : { reason }), ...(context.requestId === undefined ? {} : { requestId: context.requestId }), correlationId: context.correlationId }); if (decision.effect === "DENY") throw new Error(decision.reasonCode); }
  #store(item: Verification): void { this.#verifications.set(item.id, item); this.#history.set(item.id, [...(this.#history.get(item.id) ?? []), item]); }
  #replace(current: Verification, context: Context, changes: Readonly<Partial<Verification>>, eventType: string, action: string, reason: string): Verification { const occurredAt = this.#clock().toISOString(); const status = changes.status ?? current.status; const statusHistory = status === current.status ? current.statusHistory : [...current.statusHistory, { status, actorId: context.actor.principalId, occurredAt, reason }]; const updated = immutable<Verification>({ ...current, ...changes, statusHistory, version: current.version + 1 }); this.#store(updated); this.#record(eventType, action, updated, context, { status: updated.status, reasonRecorded: true, managerOverride: updated.approvalHistory.at(-1)?.managerOverride ?? false, fieldScope: updated.fields }); return updated; }
  #createAvailability(verification: Verification): void { const field = verification.fieldResults.find((item) => item.field === "AVAILABILITY"); if (field === undefined) return; this.#availability.set(verification.id, immutable<Availability>({ id: this.#idFactory(), version: 1, offerRef: verification.subjectRef, verificationId: verification.id, status: "AVAILABLE", asOf: field.validFrom, expiresAt: field.validUntil, classification: "CONFIDENTIAL_BUSINESS" })); }
  #restrictAvailability(verificationId: string, status: "EXPIRED" | "REVOKED"): void { const current = this.#availability.get(verificationId); if (current !== undefined) this.#availability.set(verificationId, immutable({ ...current, status })); }
  #record(eventType: string, action: string, verification: Verification, context: Context, details: Readonly<Record<string, unknown>>): void { this.#audit.append({ eventType, principal: principal(context.actor), action, target: { type: "Verification", id: verification.id, version: verification.version }, purpose: context.purpose, policyVersion: this.#policyVersion, classification: verification.classification, decision: "ALLOW", outcome: "COMPLETED", ...(context.requestId === undefined ? {} : { requestId: context.requestId }), correlationId: context.correlationId, details: { ...details, teamId: verification.teamId, evidenceHandling: "REFERENCE_ONLY", contactDataIncluded: false } }); }
}
