import type { AuditPrincipal, AuditSink, Clock, DataClassification, IdFactory } from "../../../packages/security-contracts/src/index.js";
import { validateAdvisoryResult, type AdvisoryValidationDecision, type AiCapabilityId } from "../../ai/src/advisory-ai-service.js";
import type { AuthorizationService } from "../../authorization/src/authorization-service.js";
import type { SessionContext } from "../../identity/src/session-service.js";

export type MatchingFactor = "LOCATION" | "PROPERTY_TYPE" | "BUDGET" | "BEDROOMS" | "AREA" | "OPTIONAL_PREFERENCES";
export interface RequirementMatchSnapshot { readonly id: string; readonly version: number; readonly teamId: string; readonly status: "ACTIVE" | "DRAFT" | "PAUSED" | "FULFILLED" | "WITHDRAWN" | "EXPIRED"; readonly classification: "RESTRICTED_PERSONAL"; readonly locations: readonly string[]; readonly propertyTypes: readonly string[]; readonly budget?: Readonly<{ readonly lower?: number; readonly upper?: number }>; readonly bedrooms?: Readonly<{ readonly minimum?: number; readonly maximum?: number }>; readonly area?: Readonly<{ readonly minimum?: number; readonly maximum?: number }>; readonly optionalPreferences: readonly string[]; readonly hardCriteria: readonly MatchingFactor[] }
export interface CandidateMatchSnapshot { readonly id: string; readonly version: number; readonly teamId: string; readonly status: "captured" | "parsed" | "review" | "candidate" | "verification-pending" | "expired" | "withdrawn" | "deleted"; readonly classification: "CONFIDENTIAL_BUSINESS"; readonly offerId: string; readonly offerVersion: number; readonly offerStatus: "draft" | "active" | "expired" | "withdrawn" | "superseded" | "deleted"; readonly locationId?: string; readonly propertyType?: string; readonly price?: number; readonly bedrooms?: number; readonly area?: number; readonly optionalPreferences: readonly string[]; readonly unresolvedCritical: boolean }
export interface VersionedReference { readonly id: string; readonly version: number }
export interface RankingComponent { readonly factor: MatchingFactor; readonly weight: 30 | 25 | 20 | 15 | 5; readonly fit: number; readonly contribution: number; readonly outcome: "PASS" | "FAIL" | "UNKNOWN"; readonly reasonCode: string }
export type MatchStatus = "REVIEW_REQUIRED" | "REVIEWED" | "ACCEPTED" | "REJECTED" | "STALE" | "SUPERSEDED";
export interface MatchDisposition { readonly actorId: string; readonly status: MatchStatus; readonly reason: string; readonly occurredAt: string }
export interface MatchResult { readonly id: string; readonly version: number; readonly runId: string; readonly teamId: string; readonly status: MatchStatus; readonly authority: "ADVISORY"; readonly classification: "RESTRICTED_PERSONAL"; readonly requirementRef: VersionedReference; readonly candidateRef: VersionedReference; readonly offerRef: VersionedReference; readonly hardEligibility: "PASS"; readonly hardMatchCount: number; readonly score: number; readonly budgetFit: number; readonly rank: number; readonly components: readonly RankingComponent[]; readonly explanation: Readonly<{ readonly kind: "DETERMINISTIC"; readonly reasonCodes: readonly string[]; readonly limitations: readonly string[] }>; readonly matcherVersion: "deterministic-matching-v1"; readonly policyVersion: string; readonly calculatedAt: string; readonly staleReason?: string; readonly reviewHistory: readonly MatchDisposition[] }
export interface MatchRun { readonly id: string; readonly version: 1; readonly teamId: string; readonly status: "REVIEW_REQUIRED" | "EMPTY"; readonly authority: "ADVISORY"; readonly requirementRef: VersionedReference; readonly cohortSize: number; readonly results: readonly MatchResult[]; readonly reviewResults: readonly MatchResult[]; readonly requestedBy: string; readonly calculatedAt: string; readonly policyVersion: string }

interface Dependencies { readonly authorizationService: AuthorizationService; readonly auditSink: AuditSink; readonly clock: Clock; readonly idFactory: IdFactory; readonly policyVersion: string }
interface Context { readonly actor: SessionContext; readonly purpose: string; readonly correlationId: string; readonly requestId?: string }
interface IdempotencyRecord { readonly fingerprint: string; readonly runId: string }
const weights: Readonly<Record<MatchingFactor, RankingComponent["weight"]>> = Object.freeze({ LOCATION: 30, PROPERTY_TYPE: 25, BUDGET: 20, BEDROOMS: 15, AREA: 5, OPTIONAL_PREFERENCES: 5 });
const factorOrder: readonly MatchingFactor[] = Object.freeze(["LOCATION", "PROPERTY_TYPE", "BUDGET", "BEDROOMS", "AREA", "OPTIONAL_PREFERENCES"]);

function deepFreeze(value: unknown): void { if (value !== null && typeof value === "object" && !Object.isFrozen(value)) { Object.values(value).forEach(deepFreeze); Object.freeze(value); } }
function immutable<T>(value: T): T { const copy = structuredClone(value); deepFreeze(copy); return copy; }
function principal(session: SessionContext): AuditPrincipal { return { id: session.principalId, type: session.principalType, roles: session.roles, ...(session.teamId === undefined ? {} : { teamId: session.teamId }), sessionId: session.id }; }
function boundedFit(value: number): number { return Math.max(0, Math.min(100, Math.round(value))); }
function rangeFit(value: number | undefined, range: Readonly<{ readonly minimum?: number; readonly maximum?: number }> | undefined): number | undefined { if (range === undefined) return 100; if (value === undefined) return undefined; if (range.minimum !== undefined && value < range.minimum) return boundedFit((value / Math.max(range.minimum, 1)) * 100); if (range.maximum !== undefined && value > range.maximum) return boundedFit((range.maximum / Math.max(value, 1)) * 100); return 100; }
function budgetFit(price: number | undefined, budget: RequirementMatchSnapshot["budget"]): number | undefined { if (budget === undefined) return 100; if (price === undefined) return undefined; if (budget.lower !== undefined && price < budget.lower) return boundedFit((price / Math.max(budget.lower, 1)) * 100); if (budget.upper !== undefined && price > budget.upper) return boundedFit((budget.upper / Math.max(price, 1)) * 100); return 100; }

export class MatchingService {
  readonly #authorization: AuthorizationService; readonly #audit: AuditSink; readonly #clock: Clock; readonly #idFactory: IdFactory; readonly #policyVersion: string;
  readonly #runs = new Map<string, MatchRun>(); readonly #results = new Map<string, MatchResult>(); readonly #history = new Map<string, MatchResult[]>(); readonly #idempotency = new Map<string, IdempotencyRecord>();
  public constructor(dependencies: Dependencies) { this.#authorization = dependencies.authorizationService; this.#audit = dependencies.auditSink; this.#clock = dependencies.clock; this.#idFactory = dependencies.idFactory; this.#policyVersion = dependencies.policyVersion; }

  public requestMatch(request: Context & { readonly requirement: RequirementMatchSnapshot; readonly candidates: readonly CandidateMatchSnapshot[]; readonly idempotencyKey: string }): MatchRun {
    if (request.requirement.status !== "ACTIVE") throw new Error("REQUIREMENT_NOT_ACTIVE");
    if (request.actor.teamId !== request.requirement.teamId || request.idempotencyKey.trim().length === 0) throw new Error("MATCH_REQUEST_DENIED");
    this.#authorize(request, "matching.request", "MatchRun", "new", request.requirement.teamId);
    const fingerprint = JSON.stringify({ requirement: request.requirement, candidates: request.candidates, purpose: request.purpose }); const key = `${request.actor.principalId}:${request.idempotencyKey}`; const prior = this.#idempotency.get(key);
    if (prior !== undefined) { if (prior.fingerprint !== fingerprint) throw new Error("IDEMPOTENCY_CONFLICT"); return this.#run(prior.runId); }
    const eligible = request.candidates.filter((item) => this.#baseEligible(item, request.requirement.teamId)).map((item) => ({ candidate: item, components: this.#components(request.requirement, item) })).filter((item) => this.#hardEligible(request.requirement, item.components));
    if (eligible.length > 100) throw new Error("MATCH_COHORT_LIMIT_EXCEEDED");
    const runId = this.#idFactory(); const calculatedAt = this.#clock().toISOString();
    const ranked = eligible.map(({ candidate: item, components }) => ({ candidate: item, components, hardMatchCount: request.requirement.hardCriteria.length, score: components.reduce((sum, component) => sum + component.contribution, 0), budgetFit: components.find((component) => component.factor === "BUDGET")?.fit ?? 0 })).sort((left, right) => right.score - left.score || right.hardMatchCount - left.hardMatchCount || right.budgetFit - left.budgetFit || right.candidate.version - left.candidate.version || left.candidate.id.localeCompare(right.candidate.id));
    const results = ranked.map((item, index) => { const result = immutable<MatchResult>({ id: this.#idFactory(), version: 1, runId, teamId: request.requirement.teamId, status: "REVIEW_REQUIRED", authority: "ADVISORY", classification: "RESTRICTED_PERSONAL", requirementRef: { id: request.requirement.id, version: request.requirement.version }, candidateRef: { id: item.candidate.id, version: item.candidate.version }, offerRef: { id: item.candidate.offerId, version: item.candidate.offerVersion }, hardEligibility: "PASS", hardMatchCount: item.hardMatchCount, score: item.score, budgetFit: item.budgetFit, rank: index + 1, components: item.components, explanation: { kind: "DETERMINISTIC", reasonCodes: item.components.map((component) => component.reasonCode), limitations: item.components.filter((component) => component.outcome === "UNKNOWN").map((component) => `${component.factor}_UNKNOWN`) }, matcherVersion: "deterministic-matching-v1", policyVersion: this.#policyVersion, calculatedAt, reviewHistory: [] }); this.#results.set(result.id, result); this.#history.set(result.id, [result]); return result; });
    const run = immutable<MatchRun>({ id: runId, version: 1, teamId: request.requirement.teamId, status: results.length === 0 ? "EMPTY" : "REVIEW_REQUIRED", authority: "ADVISORY", requirementRef: { id: request.requirement.id, version: request.requirement.version }, cohortSize: results.length, results, reviewResults: results.slice(0, 20), requestedBy: request.actor.principalId, calculatedAt, policyVersion: this.#policyVersion }); this.#runs.set(run.id, run); this.#idempotency.set(key, Object.freeze({ fingerprint, runId: run.id }));
    this.#record("MATCH_RUN_CREATED", "matching.request", "MatchRun", run.id, run.version, request, run.teamId, { cohortSize: run.cohortSize, reviewListSize: run.reviewResults.length, authority: run.authority }); return run;
  }

  public readRun(request: Context & { readonly runId: string }): MatchRun { const run = this.#run(request.runId); this.#scope(request, run.teamId, "MATCH_RUN_NOT_FOUND"); this.#authorize(request, "matching.read", "MatchRun", run.id, run.teamId, run.version); return run; }
  public readResult(request: Context & { readonly resultId: string }): MatchResult { const result = this.#result(request.resultId); this.#scope(request, result.teamId, "MATCH_RESULT_NOT_FOUND"); this.#authorize(request, "matching.read", "MatchResult", result.id, result.teamId, result.version); return result; }
  public readResultHistory(request: Context & { readonly resultId: string }): readonly MatchResult[] { const current = this.readResult(request); return Object.freeze([...(this.#history.get(current.id) ?? [])]); }
  public reviewResult(request: Context & { readonly resultId: string; readonly expectedVersion: number; readonly decision: "REVIEWED" | "ACCEPTED" | "REJECTED"; readonly reason: string }): MatchResult { const current = this.readResult(request); this.#version(current, request.expectedVersion); this.#reason(request.reason); if (current.status === "STALE" || current.status === "SUPERSEDED") throw new Error("MATCH_INPUT_STALE"); if (current.status === "ACCEPTED" || current.status === "REJECTED") throw new Error("STATE_TRANSITION_INVALID"); this.#authorize(request, "matching.review", "MatchResult", current.id, current.teamId, current.version); return this.#replace(current, request, { status: request.decision, reviewHistory: [...current.reviewHistory, { actorId: request.actor.principalId, status: request.decision, reason: request.reason, occurredAt: this.#clock().toISOString() }] }, "MATCH_RESULT_REVIEWED", "matching.review"); }
  public markStale(request: Context & { readonly resultId: string; readonly expectedVersion: number; readonly reason: string }): MatchResult { const current = this.readResult(request); this.#version(current, request.expectedVersion); this.#reason(request.reason); if (current.status === "STALE" || current.status === "SUPERSEDED") throw new Error("MATCH_INPUT_STALE"); this.#authorize(request, "matching.stale", "MatchResult", current.id, current.teamId, current.version); return this.#replace(current, request, { status: "STALE", staleReason: request.reason, reviewHistory: [...current.reviewHistory, { actorId: request.actor.principalId, status: "STALE", reason: request.reason, occurredAt: this.#clock().toISOString() }] }, "MATCH_RESULT_STALE", "matching.stale"); }
  public validateExplanation(request: Context & { readonly resultId: string; readonly expectedVersion: number; readonly capabilityId: Extract<AiCapabilityId, "AI-005" | "AI-006" | "AI-007">; readonly result: unknown }): AdvisoryValidationDecision { const current = this.readResult(request); this.#version(current, request.expectedVersion); const decision = validateAdvisoryResult({ expectedCapabilityId: request.capabilityId, expectedSubject: { entityType: "MatchResult", entityId: current.id, version: current.version }, inputClassifications: [current.classification], result: request.result }); this.#record("MATCH_AI_RESULT_VALIDATED", "matching.read", "MatchResult", current.id, current.version, request, current.teamId, { capabilityId: request.capabilityId, validationStatus: decision.status, route: decision.route, authority: "ADVISORY", rawContentLogged: false }); return decision; }

  #components(requirement: RequirementMatchSnapshot, candidate: CandidateMatchSnapshot): readonly RankingComponent[] {
    const values: Readonly<Record<MatchingFactor, number | undefined>> = {
      LOCATION: requirement.locations.length === 0 ? 100 : candidate.locationId === undefined ? undefined : requirement.locations.includes(candidate.locationId) ? 100 : 0,
      PROPERTY_TYPE: requirement.propertyTypes.length === 0 ? 100 : candidate.propertyType === undefined ? undefined : requirement.propertyTypes.includes(candidate.propertyType) ? 100 : 0,
      BUDGET: budgetFit(candidate.price, requirement.budget),
      BEDROOMS: rangeFit(candidate.bedrooms, requirement.bedrooms),
      AREA: rangeFit(candidate.area, requirement.area),
      OPTIONAL_PREFERENCES: requirement.optionalPreferences.length === 0 ? 100 : boundedFit((requirement.optionalPreferences.filter((item) => candidate.optionalPreferences.includes(item)).length / requirement.optionalPreferences.length) * 100),
    };
    const components: RankingComponent[] = factorOrder.map((factor) => {
      const value = values[factor]; const fit = value ?? 0;
      return { factor, weight: weights[factor], fit, contribution: Math.round((fit * weights[factor]) / 100), outcome: value === undefined ? "UNKNOWN" : value === 100 ? "PASS" : "FAIL", reasonCode: `${factor}_${value === undefined ? "UNKNOWN" : value === 100 ? "MATCH" : "MISMATCH"}` };
    });
    return immutable(components);
  }
  #hardEligible(requirement: RequirementMatchSnapshot, components: readonly RankingComponent[]): boolean { return requirement.hardCriteria.every((factor) => components.find((item) => item.factor === factor)?.outcome === "PASS"); }
  #baseEligible(candidate: CandidateMatchSnapshot, teamId: string): boolean { return candidate.teamId === teamId && (candidate.status === "candidate" || candidate.status === "verification-pending") && candidate.offerStatus === "active" && !candidate.unresolvedCritical; }
  #run(id: string): MatchRun { const item = this.#runs.get(id); if (item === undefined) throw new Error("MATCH_RUN_NOT_FOUND"); return item; }
  #result(id: string): MatchResult { const item = this.#results.get(id); if (item === undefined) throw new Error("MATCH_RESULT_NOT_FOUND"); return item; }
  #version(result: MatchResult, expected: number): void { if (result.version !== expected) throw new Error("VERSION_CONFLICT"); }
  #reason(reason: string): void { if (reason.trim().length === 0) throw new Error("REASON_REQUIRED"); }
  #scope(context: Context, teamId: string, code: string): void { if (context.actor.teamId !== teamId) throw new Error(code); }
  #authorize(context: Context, action: string, type: string, id: string, teamId: string, version?: number): void { const decision = this.#authorization.evaluate({ session: context.actor, action, resource: { type, id, teamId, ...(version === undefined ? {} : { version }) }, purpose: context.purpose, ...(context.requestId === undefined ? {} : { requestId: context.requestId }), correlationId: context.correlationId }); if (decision.effect === "DENY") throw new Error(decision.reasonCode); }
  #replace(current: MatchResult, context: Context & { readonly reason: string }, changes: Readonly<Partial<MatchResult>>, eventType: string, action: string): MatchResult { const updated = immutable<MatchResult>({ ...current, ...changes, version: current.version + 1 }); this.#results.set(updated.id, updated); this.#history.set(updated.id, [...(this.#history.get(updated.id) ?? []), updated]); this.#record(eventType, action, "MatchResult", updated.id, updated.version, context, updated.teamId, { status: updated.status, authority: updated.authority, reason: context.reason }); return updated; }
  #record(eventType: string, action: string, type: string, id: string, version: number, context: Context, teamId: string, details: Readonly<Record<string, unknown>>): void { this.#audit.append({ eventType, principal: principal(context.actor), action, target: { type, id, version }, purpose: context.purpose, policyVersion: this.#policyVersion, classification: "RESTRICTED_PERSONAL" satisfies DataClassification, decision: "ALLOW", outcome: "COMPLETED", ...(context.requestId === undefined ? {} : { requestId: context.requestId }), correlationId: context.correlationId, details: { ...details, teamId, contactDataIncluded: false } }); }
}
