import type { AdvisoryValidationDecision } from "../../../modules/ai/src/advisory-ai-service.js";
import type { SessionContext } from "../../../modules/identity/src/session-service.js";
import type { CandidateMatchSnapshot, MatchResult, MatchRun, MatchingService, RequirementMatchSnapshot, VersionedReference } from "../../../modules/matching/src/matching-service.js";
import { executeBoundary, requireSessionId, type ApiResponse, type RequestContext } from "./contracts.js";

type MatchingPort = Pick<MatchingService, "requestMatch" | "readRun" | "readResult" | "readResultHistory" | "reviewResult" | "markStale" | "validateExplanation">;
export interface MatchingInputResolverRequest { readonly actor: SessionContext; readonly purpose: string; readonly correlationId: string; readonly requestId?: string; readonly requirementRef: VersionedReference; readonly candidateRefs: readonly VersionedReference[] }
export interface MatchingInputResolver { resolve(request: MatchingInputResolverRequest): Readonly<{ readonly requirement: RequirementMatchSnapshot; readonly candidates: readonly CandidateMatchSnapshot[] }> }
export interface MatchingApiDependencies { readonly matchingService: MatchingPort; readonly matchingInputResolver: MatchingInputResolver; readonly sessionReader: (sessionId: string) => SessionContext }
type Contextual<T> = Omit<T, "actor" | "requestId" | "correlationId"> & { readonly context: RequestContext };
export interface RequestMatchInput { readonly context: RequestContext; readonly requirementRef: VersionedReference; readonly candidateRefs: readonly VersionedReference[]; readonly idempotencyKey: string; readonly purpose: string }
export type MatchingWorkspaceAction = "READ" | "REQUEST_MATCH" | "REVIEW" | "MARK_STALE";
export interface MatchingWorkspaceAccessibility { readonly landmarkLabel: "Matching review workspace"; readonly resultListLabel: "Ranked candidate matches"; readonly liveRegion: "polite"; readonly keyboardOperable: true; readonly errorSummaryLinked: true }
export interface MatchingWorkspaceView { readonly screenId: "UI-024"; readonly presentationState: "REVIEW_REQUIRED" | "EMPTY" | "STALE" | "SUPERSEDED" | "REVIEWED" | "ACCEPTED" | "REJECTED"; readonly authority: "ADVISORY"; readonly run?: MatchRun; readonly result?: MatchResult; readonly reviewResults: readonly MatchResult[]; readonly allowedActions: readonly MatchingWorkspaceAction[]; readonly accessibility: MatchingWorkspaceAccessibility }

const accessibility: MatchingWorkspaceAccessibility = Object.freeze({ landmarkLabel: "Matching review workspace", resultListLabel: "Ranked candidate matches", liveRegion: "polite", keyboardOperable: true, errorSummaryLinked: true });
function actions(actor: SessionContext): readonly MatchingWorkspaceAction[] { if (actor.roles.some((role) => role === "AGT" || role === "SAG")) return Object.freeze(["READ", "REQUEST_MATCH", "REVIEW", "MARK_STALE"]); if (actor.roles.includes("REV")) return Object.freeze(["READ", "REVIEW"]); return Object.freeze(["READ"]); }
function runView(run: MatchRun, actor: SessionContext): MatchingWorkspaceView { return Object.freeze({ screenId: "UI-024", presentationState: run.status, authority: "ADVISORY", run, reviewResults: run.reviewResults, allowedActions: actions(actor), accessibility }); }
function resultView(result: MatchResult, actor: SessionContext): MatchingWorkspaceView { return Object.freeze({ screenId: "UI-024", presentationState: result.status, authority: "ADVISORY", result, reviewResults: [result], allowedActions: actions(actor), accessibility }); }

export class MatchingApi {
  public constructor(private readonly dependencies: MatchingApiDependencies) {}
  public requestMatch(input: RequestMatchInput): ApiResponse<MatchingWorkspaceView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); const resolved = this.dependencies.matchingInputResolver.resolve({ actor, purpose: input.purpose, correlationId: input.context.correlationId, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), requirementRef: input.requirementRef, candidateRefs: input.candidateRefs }); const run = this.dependencies.matchingService.requestMatch({ actor, purpose: input.purpose, correlationId: input.context.correlationId, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), requirement: resolved.requirement, candidates: resolved.candidates, idempotencyKey: input.idempotencyKey }); return runView(run, actor); }); }
  public readRun(input: Contextual<Parameters<MatchingService["readRun"]>[0]>): ApiResponse<MatchingWorkspaceView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); return runView(this.dependencies.matchingService.readRun(this.#request(input, actor)), actor); }); }
  public readResult(input: Contextual<Parameters<MatchingService["readResult"]>[0]>): ApiResponse<MatchingWorkspaceView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); return resultView(this.dependencies.matchingService.readResult(this.#request(input, actor)), actor); }); }
  public readResultHistory(input: Contextual<Parameters<MatchingService["readResultHistory"]>[0]>): ApiResponse<ReturnType<MatchingService["readResultHistory"]>> { return executeBoundary(input.context, () => this.dependencies.matchingService.readResultHistory(this.#request(input, this.#actor(input.context)))); }
  public reviewResult(input: Contextual<Parameters<MatchingService["reviewResult"]>[0]>): ApiResponse<MatchingWorkspaceView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); return resultView(this.dependencies.matchingService.reviewResult(this.#request(input, actor)), actor); }); }
  public markStale(input: Contextual<Parameters<MatchingService["markStale"]>[0]>): ApiResponse<MatchingWorkspaceView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); return resultView(this.dependencies.matchingService.markStale(this.#request(input, actor)), actor); }); }
  public validateExplanation(input: Contextual<Parameters<MatchingService["validateExplanation"]>[0]>): ApiResponse<AdvisoryValidationDecision> { return executeBoundary(input.context, () => this.dependencies.matchingService.validateExplanation(this.#request(input, this.#actor(input.context)))); }
  #request<T extends Readonly<Record<string, unknown>>>(input: T & { readonly context: RequestContext }, actor: SessionContext): Omit<T, "context"> & { readonly actor: SessionContext; readonly correlationId: string; readonly requestId?: string } { const { context, ...fields } = input; return { ...fields, actor, correlationId: context.correlationId, ...(context.requestId === undefined ? {} : { requestId: context.requestId }) }; }
  #actor(context: RequestContext): SessionContext { return this.dependencies.sessionReader(requireSessionId(context)); }
}
