import type { SessionContext } from "../../../modules/identity/src/session-service.js";
import type { ApprovalReviewContext, EffectiveApprovalDecision, ImmutableRepresentationSnapshot, PublicationApproval, PublicationApprovalService } from "../../../modules/publication-approval/src/publication-approval-service.js";
import type { ClientProposal, ProposalService } from "../../../modules/proposal/src/proposal-service.js";
import { executeBoundary, requireSessionId, type ApiResponse, type RequestContext } from "./contracts.js";

type ProposalPort = Pick<ProposalService, "createProposal" | "readProposal" | "reviewProposal" | "recordProposalShare" | "recordProposalFeedback">;
type ApprovalPort = Pick<PublicationApprovalService, "createRepresentationSnapshot" | "readApproval" | "listApprovalQueue" | "getApprovalReviewContext" | "checkEffectiveApproval" | "createApprovalRequest" | "assignOrClaimApprover" | "reassignOrReleaseApprover" | "decideApproval" | "revokeApproval" | "expireApproval">;
export interface ProposalApprovalApiDependencies { readonly proposalService: ProposalPort; readonly publicationApprovalService: ApprovalPort; readonly sessionReader: (sessionId: string) => SessionContext }
type Contextual<T> = Omit<T, "actor" | "requestId" | "correlationId"> & { readonly context: RequestContext };
export type ProposalUiAction = "READ" | "CREATE" | "SUBMIT" | "REVIEW" | "SHARE" | "FEEDBACK";
export type ApprovalUiAction = "READ" | "CLAIM" | "RELEASE" | "REASSIGN" | "APPROVE" | "REJECT" | "REVOKE";
export interface ApprovalAccessibility { readonly landmarkLabel: string; readonly listLabel: string; readonly liveRegion: "polite"; readonly keyboardOperable: true; readonly errorSummaryLinked: true }
export interface ProposalView { readonly screenId: "UI-025"; readonly presentationState: ClientProposal["status"]; readonly proposal: ClientProposal; readonly allowedActions: readonly ProposalUiAction[] }
export interface ApprovalQueueItemView { readonly approval: PublicationApproval; readonly actorConflictReasonCodes: readonly string[]; readonly prerequisiteValid: boolean; readonly eligibility: "ELIGIBLE" | "CONFLICTED" | "NOT_PUA"; readonly expiryRisk: "ACTIVE" | "EXPIRING"; readonly allowedActions: readonly ApprovalUiAction[] }
export interface ApprovalQueueView { readonly screenId: "UI-029"; readonly presentationState: "READY" | "EMPTY"; readonly items: readonly ApprovalQueueItemView[]; readonly allowedActions: readonly ApprovalUiAction[]; readonly accessibility: ApprovalAccessibility }
export interface ApprovalDetailView { readonly screenId: "UI-030"; readonly presentationState: PublicationApproval["status"]; readonly approval: PublicationApproval; readonly reviewContext?: ApprovalReviewContext; readonly allowedActions: readonly ApprovalUiAction[]; readonly accessibility: ApprovalAccessibility }

const queueAccessibility: ApprovalAccessibility = Object.freeze({ landmarkLabel: "Publication approval queue", listLabel: "Scoped publication approvals", liveRegion: "polite", keyboardOperable: true, errorSummaryLinked: true });
const detailAccessibility: ApprovalAccessibility = Object.freeze({ landmarkLabel: "Publication approval review", listLabel: "Exact representation, prerequisites and immutable history", liveRegion: "polite", keyboardOperable: true, errorSummaryLinked: true });
function proposalActions(actor: SessionContext): readonly ProposalUiAction[] { if (actor.roles.includes("SAG")) return Object.freeze(["READ", "CREATE", "SUBMIT", "REVIEW", "SHARE", "FEEDBACK"]); if (actor.roles.includes("AGT")) return Object.freeze(["READ", "CREATE", "SUBMIT", "SHARE", "FEEDBACK"]); return Object.freeze(["READ"]); }
function approvalActions(actor: SessionContext, approval?: PublicationApproval, reviewContext?: ApprovalReviewContext): readonly ApprovalUiAction[] { if (!actor.roles.includes("PUA")) return Object.freeze(["READ"]); if (approval === undefined) return Object.freeze(["READ"]); if (reviewContext === undefined || !reviewContext.actorEligible || reviewContext.actorConflictReasonCodes.length > 0 || !reviewContext.verificationValid || !reviewContext.permissionValid || !reviewContext.targetPolicyValid) return Object.freeze(["READ"]); if (approval.status === "REQUESTED") return Object.freeze(["READ", "CLAIM"]); if (approval.status === "UNDER_REVIEW" && approval.assignedApproverActorId === actor.principalId) return Object.freeze(["READ", "RELEASE", "REASSIGN", "APPROVE", "REJECT"]); if (approval.status === "APPROVED") return Object.freeze(["READ", "REVOKE"]); return Object.freeze(["READ"]); }
function proposalView(proposal: ClientProposal, actor: SessionContext): ProposalView { return Object.freeze({ screenId: "UI-025", presentationState: proposal.status, proposal, allowedActions: proposalActions(actor) }); }
function detailView(approval: PublicationApproval, actor: SessionContext, reviewContext?: ApprovalReviewContext): ApprovalDetailView { return Object.freeze({ screenId: "UI-030", presentationState: approval.status, approval, ...(reviewContext === undefined ? {} : { reviewContext }), allowedActions: approvalActions(actor, approval, reviewContext), accessibility: detailAccessibility }); }

export class ProposalApprovalApi {
  public constructor(private readonly dependencies: ProposalApprovalApiDependencies) {}
  public createProposal(input: Contextual<Parameters<ProposalService["createProposal"]>[0]>): ApiResponse<ProposalView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); return proposalView(this.dependencies.proposalService.createProposal(this.#request(input, actor)), actor); }); }
  public readProposal(input: Contextual<Parameters<ProposalService["readProposal"]>[0]>): ApiResponse<ProposalView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); return proposalView(this.dependencies.proposalService.readProposal(this.#request(input, actor)), actor); }); }
  public reviewProposal(input: Contextual<Parameters<ProposalService["reviewProposal"]>[0]>): ApiResponse<ProposalView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); return proposalView(this.dependencies.proposalService.reviewProposal(this.#request(input, actor)), actor); }); }
  public recordProposalShare(input: Contextual<Parameters<ProposalService["recordProposalShare"]>[0]>): ApiResponse<ProposalView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); return proposalView(this.dependencies.proposalService.recordProposalShare(this.#request(input, actor)), actor); }); }
  public recordProposalFeedback(input: Contextual<Parameters<ProposalService["recordProposalFeedback"]>[0]>): ApiResponse<ProposalView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); return proposalView(this.dependencies.proposalService.recordProposalFeedback(this.#request(input, actor)), actor); }); }
  public createRepresentationSnapshot(input: Contextual<Parameters<PublicationApprovalService["createRepresentationSnapshot"]>[0]>): ApiResponse<ImmutableRepresentationSnapshot> { return executeBoundary(input.context, () => this.dependencies.publicationApprovalService.createRepresentationSnapshot(this.#request(input, this.#actor(input.context)))); }
  public readApproval(input: Contextual<Parameters<PublicationApprovalService["readApproval"]>[0]>): ApiResponse<ApprovalDetailView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); return detailView(this.dependencies.publicationApprovalService.readApproval(this.#request(input, actor)), actor); }); }
  public listApprovalQueue(input: Contextual<Parameters<PublicationApprovalService["listApprovalQueue"]>[0]>): ApiResponse<ApprovalQueueView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); const approvals = this.dependencies.publicationApprovalService.listApprovalQueue(this.#request(input, actor)); const now = Date.now(); const items = approvals.map((approval) => { const reviewContext = this.dependencies.publicationApprovalService.getApprovalReviewContext({ actor, purpose: input.purpose, correlationId: input.context.correlationId, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), approvalId: approval.id }); const conflicted = reviewContext.actorConflictReasonCodes.length > 0; return Object.freeze({ approval, actorConflictReasonCodes: reviewContext.actorConflictReasonCodes, prerequisiteValid: reviewContext.verificationValid && reviewContext.permissionValid && reviewContext.targetPolicyValid, eligibility: !actor.roles.includes("PUA") || !reviewContext.actorEligible ? "NOT_PUA" as const : conflicted ? "CONFLICTED" as const : "ELIGIBLE" as const, expiryRisk: new Date(approval.expiresAt).getTime() - now <= 86_400_000 ? "EXPIRING" as const : "ACTIVE" as const, allowedActions: approvalActions(actor, approval, reviewContext) }); }); return Object.freeze({ screenId: "UI-029", presentationState: items.length === 0 ? "EMPTY" : "READY", items: Object.freeze(items), allowedActions: Object.freeze(["READ"] as const), accessibility: queueAccessibility }); }); }
  public getApprovalReviewContext(input: Contextual<Parameters<PublicationApprovalService["getApprovalReviewContext"]>[0]>): ApiResponse<ApprovalDetailView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); const reviewContext = this.dependencies.publicationApprovalService.getApprovalReviewContext(this.#request(input, actor)); return detailView(reviewContext.approval, actor, reviewContext); }); }
  public checkEffectiveApproval(input: Contextual<Parameters<PublicationApprovalService["checkEffectiveApproval"]>[0]>): ApiResponse<EffectiveApprovalDecision> { return executeBoundary(input.context, () => this.dependencies.publicationApprovalService.checkEffectiveApproval(this.#request(input, this.#actor(input.context)))); }
  public createApprovalRequest(input: Contextual<Parameters<PublicationApprovalService["createApprovalRequest"]>[0]>): ApiResponse<ApprovalDetailView> { return this.#approvalMutation(input, "createApprovalRequest"); }
  public assignOrClaimApprover(input: Contextual<Parameters<PublicationApprovalService["assignOrClaimApprover"]>[0]>): ApiResponse<ApprovalDetailView> { return this.#approvalMutation(input, "assignOrClaimApprover"); }
  public reassignOrReleaseApprover(input: Contextual<Parameters<PublicationApprovalService["reassignOrReleaseApprover"]>[0]>): ApiResponse<ApprovalDetailView> { return this.#approvalMutation(input, "reassignOrReleaseApprover"); }
  public decideApproval(input: Contextual<Parameters<PublicationApprovalService["decideApproval"]>[0]>): ApiResponse<ApprovalDetailView> { return this.#approvalMutation(input, "decideApproval"); }
  public revokeApproval(input: Contextual<Parameters<PublicationApprovalService["revokeApproval"]>[0]>): ApiResponse<ApprovalDetailView> { return this.#approvalMutation(input, "revokeApproval"); }
  public expireApproval(input: Contextual<Parameters<PublicationApprovalService["expireApproval"]>[0]>): ApiResponse<ApprovalDetailView> { return this.#approvalMutation(input, "expireApproval"); }
  #approvalMutation<K extends "createApprovalRequest" | "assignOrClaimApprover" | "reassignOrReleaseApprover" | "decideApproval" | "revokeApproval" | "expireApproval">(input: Contextual<Parameters<PublicationApprovalService[K]>[0]>, method: K): ApiResponse<ApprovalDetailView> { return executeBoundary(input.context, () => { const actor = this.#actor(input.context); const request = this.#request(input, actor); const operation = this.dependencies.publicationApprovalService[method] as (value: typeof request) => PublicationApproval; return detailView(operation(request), actor); }); }
  #request<T extends Readonly<Record<string, unknown>>>(input: T & { readonly context: RequestContext }, actor: SessionContext): Omit<T, "context"> & { readonly actor: SessionContext; readonly correlationId: string; readonly requestId?: string } { const { context, ...fields } = input; return { ...fields, actor, correlationId: context.correlationId, ...(context.requestId === undefined ? {} : { requestId: context.requestId }) }; }
  #actor(context: RequestContext): SessionContext { return this.dependencies.sessionReader(requireSessionId(context)); }
}
