import type { SessionContext } from "../../../modules/identity/src/session-service.js";
import type { CandidateListing, DuplicateGroup, ListingOffer, ListingService } from "../../../modules/listing/src/listing-service.js";
import type { PropertyAlias, PropertyNode, PropertyService } from "../../../modules/property/src/property-service.js";
import { executeBoundary, requireSessionId, type ApiResponse, type RequestContext } from "./contracts.js";

type PropertyPort = Pick<PropertyService, "propose" | "decide" | "proposeAlias" | "search" | "readForActor">;
type ListingPort = Pick<ListingService, "createCandidate" | "reviseCandidate" | "createOffer" | "reviseOffer" | "suggestDuplicate" | "disposeDuplicate" | "readCandidateForActor" | "listCandidates" | "readDuplicateForActor">;
export interface PropertyListingApiDependencies { readonly propertyService: PropertyPort; readonly listingService: ListingPort; readonly sessionReader: (sessionId: string) => SessionContext }
type Contextual<T> = Omit<T, "actor" | "requestId" | "correlationId"> & { readonly context: RequestContext };

export interface PropertyViewState { readonly presentationState: "READY"; readonly canonicalState: PropertyNode["status"]; readonly authority: PropertyNode["authority"]; readonly record: PropertyNode }
export interface AliasViewState { readonly presentationState: "REVIEW_REQUIRED"; readonly canonicalState: PropertyAlias["status"]; readonly authority: "LOOKUP_EVIDENCE"; readonly record: PropertyAlias }
export interface CandidateViewState { readonly presentationState: "READY"; readonly canonicalState: CandidateListing["status"]; readonly authority: CandidateListing["authority"]; readonly record: CandidateListing }
export interface OfferViewState { readonly presentationState: "READY"; readonly canonicalState: ListingOffer["status"]; readonly authority: ListingOffer["authority"]; readonly record: ListingOffer }
export interface DuplicateViewState { readonly presentationState: "REVIEW_REQUIRED" | "READY"; readonly canonicalState: DuplicateGroup["status"]; readonly authority: DuplicateGroup["authority"]; readonly record: DuplicateGroup }

function propertyView(record: PropertyNode): PropertyViewState { return Object.freeze({ presentationState: "READY", canonicalState: record.status, authority: record.authority, record }); }
function aliasView(record: PropertyAlias): AliasViewState { return Object.freeze({ presentationState: "REVIEW_REQUIRED", canonicalState: record.status, authority: "LOOKUP_EVIDENCE", record }); }
function candidateView(record: CandidateListing): CandidateViewState { return Object.freeze({ presentationState: "READY", canonicalState: record.status, authority: record.authority, record }); }
function offerView(record: ListingOffer): OfferViewState { return Object.freeze({ presentationState: "READY", canonicalState: record.status, authority: record.authority, record }); }
function duplicateView(record: DuplicateGroup): DuplicateViewState { return Object.freeze({ presentationState: record.authority === "ADVISORY" ? "REVIEW_REQUIRED" : "READY", canonicalState: record.status, authority: record.authority, record }); }

export class PropertyListingApi {
  public constructor(private readonly dependencies: PropertyListingApiDependencies) {}
  public proposeProperty(input: Contextual<Parameters<PropertyService["propose"]>[0]>): ApiResponse<PropertyViewState> { return executeBoundary(input.context, () => propertyView(this.dependencies.propertyService.propose({ actor: this.#actor(input.context), entityType: input.entityType, canonicalName: input.canonicalName, ...(input.parentRef === undefined ? {} : { parentRef: input.parentRef }), reason: input.reason, purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }))); }
  public decideProperty(input: Contextual<Parameters<PropertyService["decide"]>[0]>): ApiResponse<PropertyViewState> { return executeBoundary(input.context, () => propertyView(this.dependencies.propertyService.decide({ actor: this.#actor(input.context), nodeId: input.nodeId, expectedVersion: input.expectedVersion, decision: input.decision, reason: input.reason, purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }))); }
  public proposeAlias(input: Contextual<Parameters<PropertyService["proposeAlias"]>[0]>): ApiResponse<AliasViewState> { return executeBoundary(input.context, () => aliasView(this.dependencies.propertyService.proposeAlias({ actor: this.#actor(input.context), targetRef: input.targetRef, alias: input.alias, language: input.language, sourceRef: input.sourceRef, confidence: input.confidence, purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }))); }
  public searchProperties(input: Contextual<Parameters<PropertyService["search"]>[0]>): ApiResponse<readonly PropertyViewState[]> { return executeBoundary(input.context, () => Object.freeze(this.dependencies.propertyService.search({ actor: this.#actor(input.context), query: input.query, purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }).map(propertyView))); }
  public readProperty(input: Contextual<Parameters<PropertyService["readForActor"]>[0]>): ApiResponse<PropertyViewState> { return executeBoundary(input.context, () => propertyView(this.dependencies.propertyService.readForActor({ actor: this.#actor(input.context), nodeId: input.nodeId, purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }))); }
  public createCandidate(input: Contextual<Parameters<ListingService["createCandidate"]>[0]>): ApiResponse<CandidateViewState> { return executeBoundary(input.context, () => candidateView(this.dependencies.listingService.createCandidate({ actor: this.#actor(input.context), ...(input.propertyRef === undefined ? {} : { propertyRef: input.propertyRef }), sourceRefs: input.sourceRefs, intakeRef: input.intakeRef, ...(input.aiResultRef === undefined ? {} : { aiResultRef: input.aiResultRef }), unresolvedFields: input.unresolvedFields, ...(input.idempotencyKey === undefined ? {} : { idempotencyKey: input.idempotencyKey }), purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }))); }
  public reviseCandidate(input: Contextual<Parameters<ListingService["reviseCandidate"]>[0]>): ApiResponse<CandidateViewState> { return executeBoundary(input.context, () => candidateView(this.dependencies.listingService.reviseCandidate({ actor: this.#actor(input.context), candidateId: input.candidateId, expectedVersion: input.expectedVersion, status: input.status, ...(input.propertyRef === undefined ? {} : { propertyRef: input.propertyRef }), unresolvedFields: input.unresolvedFields, reason: input.reason, purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }))); }
  public listCandidates(input: Contextual<Parameters<ListingService["listCandidates"]>[0]>): ApiResponse<readonly CandidateViewState[]> { return executeBoundary(input.context, () => Object.freeze(this.dependencies.listingService.listCandidates({ actor: this.#actor(input.context), ...(input.propertyId === undefined ? {} : { propertyId: input.propertyId }), purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }).map(candidateView))); }
  public readCandidate(input: Contextual<Parameters<ListingService["readCandidateForActor"]>[0]>): ApiResponse<CandidateViewState> { return executeBoundary(input.context, () => candidateView(this.dependencies.listingService.readCandidateForActor({ actor: this.#actor(input.context), candidateId: input.candidateId, purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }))); }
  public createOffer(input: Contextual<Parameters<ListingService["createOffer"]>[0]>): ApiResponse<OfferViewState> { return executeBoundary(input.context, () => offerView(this.dependencies.listingService.createOffer({ actor: this.#actor(input.context), candidateId: input.candidateId, expectedCandidateVersion: input.expectedCandidateVersion, transactionType: input.transactionType, terms: input.terms, sourceRefs: input.sourceRefs, purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }))); }
  public reviseOffer(input: Contextual<Parameters<ListingService["reviseOffer"]>[0]>): ApiResponse<OfferViewState> { return executeBoundary(input.context, () => offerView(this.dependencies.listingService.reviseOffer({ actor: this.#actor(input.context), offerId: input.offerId, expectedVersion: input.expectedVersion, status: input.status, terms: input.terms, reason: input.reason, purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }))); }
  public suggestDuplicate(input: Contextual<Parameters<ListingService["suggestDuplicate"]>[0]>): ApiResponse<DuplicateViewState> { return executeBoundary(input.context, () => duplicateView(this.dependencies.listingService.suggestDuplicate({ actor: this.#actor(input.context), subjectRefs: input.subjectRefs, aiResultRef: input.aiResultRef, relationship: input.relationship, recommendation: input.recommendation, signals: input.signals, contradictions: input.contradictions, confidence: input.confidence, purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }))); }
  public disposeDuplicate(input: Contextual<Parameters<ListingService["disposeDuplicate"]>[0]>): ApiResponse<DuplicateViewState> { return executeBoundary(input.context, () => duplicateView(this.dependencies.listingService.disposeDuplicate({ actor: this.#actor(input.context), groupId: input.groupId, expectedVersion: input.expectedVersion, decision: input.decision, reason: input.reason, purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }))); }
  public readDuplicate(input: Contextual<Parameters<ListingService["readDuplicateForActor"]>[0]>): ApiResponse<DuplicateViewState> { return executeBoundary(input.context, () => duplicateView(this.dependencies.listingService.readDuplicateForActor({ actor: this.#actor(input.context), groupId: input.groupId, purpose: input.purpose, ...(input.context.requestId === undefined ? {} : { requestId: input.context.requestId }), correlationId: input.context.correlationId }))); }
  #actor(context: RequestContext): SessionContext { return this.dependencies.sessionReader(requireSessionId(context)); }
}
