import type { AuditPrincipal, AuditSink, Clock, IdFactory } from "../../../packages/security-contracts/src/index.js";
import type { AuthorizationService } from "../../authorization/src/authorization-service.js";
import type { SessionContext } from "../../identity/src/session-service.js";
import type { CandidateDraftPort, CandidateDraftReference } from "../../intake/src/intake-service.js";

export interface ListingReference { readonly entityType: string; readonly entityId: string; readonly version: number }
export interface CandidateListing { readonly id: string; readonly version: number; readonly status: "captured" | "parsed" | "review" | "candidate" | "verification-pending" | "expired" | "withdrawn" | "deleted"; readonly authority: "CANDIDATE"; readonly propertyRef?: ListingReference; readonly sourceRefs: readonly ListingReference[]; readonly intakeRef: ListingReference; readonly aiResultRef?: ListingReference; readonly unresolvedFields: readonly string[]; readonly relatedCandidateIds: readonly string[]; readonly classification: "CONFIDENTIAL_BUSINESS"; readonly createdBy: string }
export interface ListingOffer { readonly id: string; readonly version: number; readonly candidateId: string; readonly status: "draft" | "active" | "expired" | "withdrawn" | "superseded" | "deleted"; readonly authority: "CANDIDATE_CLAIM"; readonly transactionType: string; readonly terms: Readonly<Record<string, unknown>>; readonly sourceRefs: readonly ListingReference[]; readonly classification: "CONFIDENTIAL_BUSINESS" }
export type DuplicateStatus = "DUPLICATE.SUGGESTED" | "DUPLICATE.IN_REVIEW" | "DUPLICATE.NEEDS_EVIDENCE" | "DUPLICATE.RESOLVED_LINK" | "DUPLICATE.RESOLVED_MERGE" | "DUPLICATE.RESOLVED_SEPARATE" | "DUPLICATE.REOPENED";
export interface DuplicateDecision { readonly actorId: string; readonly decision: Exclude<DuplicateStatus, "DUPLICATE.SUGGESTED" | "DUPLICATE.IN_REVIEW" | "DUPLICATE.REOPENED">; readonly reason: string; readonly occurredAt: string }
export interface DuplicateGroup { readonly id: string; readonly version: number; readonly status: DuplicateStatus; readonly authority: "ADVISORY" | "HUMAN_DISPOSITION"; readonly subjectRefs: readonly ListingReference[]; readonly aiResultRef: ListingReference; readonly relationship: string; readonly recommendation: string; readonly signals: readonly string[]; readonly contradictions: readonly string[]; readonly confidence: "HIGH" | "MEDIUM" | "LOW" | "UNKNOWN"; readonly decisionHistory: readonly DuplicateDecision[]; readonly classification: "INTERNAL"; readonly createdBy: string }

interface Dependencies { readonly authorizationService: AuthorizationService; readonly auditSink: AuditSink; readonly clock: Clock; readonly idFactory: IdFactory; readonly policyVersion: string }
interface Context { readonly actor: SessionContext; readonly purpose: string; readonly correlationId: string; readonly requestId?: string }
function deepFreeze(value: unknown): void { if (value !== null && typeof value === "object" && !Object.isFrozen(value)) { Object.values(value).forEach(deepFreeze); Object.freeze(value); } }
function immutable<T>(value: T): T { const copy = structuredClone(value); deepFreeze(copy); return copy; }
function principal(session: SessionContext): AuditPrincipal { return { id: session.principalId, type: session.principalType, roles: session.roles, ...(session.teamId === undefined ? {} : { teamId: session.teamId }), sessionId: session.id }; }

export class ListingService implements CandidateDraftPort {
  readonly #authorization: AuthorizationService; readonly #audit: AuditSink; readonly #clock: Clock; readonly #idFactory: IdFactory; readonly #policyVersion: string;
  readonly #candidates = new Map<string, CandidateListing>(); readonly #offers = new Map<string, ListingOffer>(); readonly #duplicates = new Map<string, DuplicateGroup>(); readonly #candidateIdempotency = new Map<string, Readonly<{ fingerprint: string; candidateId: string }>>();
  public constructor(dependencies: Dependencies) { this.#authorization = dependencies.authorizationService; this.#audit = dependencies.auditSink; this.#clock = dependencies.clock; this.#idFactory = dependencies.idFactory; this.#policyVersion = dependencies.policyVersion; }

  public createCandidate(request: Context & { readonly propertyRef?: ListingReference; readonly sourceRefs: readonly ListingReference[]; readonly intakeRef: ListingReference; readonly aiResultRef?: ListingReference; readonly unresolvedFields: readonly string[]; readonly idempotencyKey?: string }): CandidateListing {
    if (request.sourceRefs.length === 0) throw new Error("PROVENANCE_REQUIRED"); this.#authorize(request, "candidate.create", "CandidateListing", "new");
    const fingerprint = JSON.stringify({ propertyRef: request.propertyRef, sourceRefs: request.sourceRefs, intakeRef: request.intakeRef, aiResultRef: request.aiResultRef, unresolvedFields: request.unresolvedFields });
    if (request.idempotencyKey !== undefined) { const key = `${request.actor.principalId}:candidate.create:${request.idempotencyKey}`; const existing = this.#candidateIdempotency.get(key); if (existing !== undefined) { if (existing.fingerprint !== fingerprint) throw new Error("IDEMPOTENCY_CONFLICT"); return this.readCandidate(existing.candidateId); } }
    const candidate = immutable({ id: this.#idFactory(), version: 1, status: "candidate" as const, authority: "CANDIDATE" as const, ...(request.propertyRef === undefined ? {} : { propertyRef: request.propertyRef }), sourceRefs: request.sourceRefs, intakeRef: request.intakeRef, ...(request.aiResultRef === undefined ? {} : { aiResultRef: request.aiResultRef }), unresolvedFields: request.unresolvedFields, relatedCandidateIds: [], classification: "CONFIDENTIAL_BUSINESS" as const, createdBy: request.actor.principalId }); this.#candidates.set(candidate.id, candidate); if (request.idempotencyKey !== undefined) this.#candidateIdempotency.set(`${request.actor.principalId}:candidate.create:${request.idempotencyKey}`, Object.freeze({ fingerprint, candidateId: candidate.id })); this.#record("CANDIDATE_CREATED", "candidate.create", candidate.id, candidate.version, request); return candidate;
  }

  public reviseCandidate(request: Context & { readonly candidateId: string; readonly expectedVersion: number; readonly status: CandidateListing["status"]; readonly propertyRef?: ListingReference; readonly unresolvedFields: readonly string[]; readonly reason: string }): CandidateListing {
    const current = this.readCandidate(request.candidateId); if (current.version !== request.expectedVersion) throw new Error("VERSION_CONFLICT"); if (request.reason.trim().length === 0) throw new Error("REASON_REQUIRED"); this.#authorize(request, "candidate.revise", "CandidateListing", current.id, current.version);
    const updated = immutable({ ...current, version: current.version + 1, status: request.status, ...(request.propertyRef === undefined ? {} : { propertyRef: request.propertyRef }), unresolvedFields: request.unresolvedFields }); this.#candidates.set(updated.id, updated); this.#record("CANDIDATE_REVISED", "candidate.revise", updated.id, updated.version, request, request.reason); return updated;
  }

  public register(request: { readonly intakeId: string; readonly intakeVersion: number; readonly rawSourceId: string; readonly rawSourceVersion: number; readonly reviewedBy: string; readonly reason: string; readonly correlationId: string; readonly aiResultReference?: string }): CandidateDraftReference {
    if (request.reason.trim().length === 0) throw new Error("REASON_REQUIRED");
    const candidate = immutable({ id: this.#idFactory(), version: 1, status: "candidate" as const, authority: "CANDIDATE" as const, sourceRefs: [{ entityType: "RawSource", entityId: request.rawSourceId, version: request.rawSourceVersion }], intakeRef: { entityType: "Intake", entityId: request.intakeId, version: request.intakeVersion }, ...(request.aiResultReference === undefined ? {} : { aiResultRef: { entityType: "AiResult", entityId: request.aiResultReference, version: 1 } }), unresolvedFields: [], relatedCandidateIds: [], classification: "CONFIDENTIAL_BUSINESS" as const, createdBy: request.reviewedBy }); this.#candidates.set(candidate.id, candidate);
    this.#audit.append({ eventType: "CANDIDATE_REGISTERED_FROM_INTAKE", principal: { id: request.reviewedBy, type: "HUMAN", roles: [] }, action: "candidate.create", target: { type: "CandidateListing", id: candidate.id, version: candidate.version }, purpose: "SOURCE_INTAKE", policyVersion: this.#policyVersion, classification: candidate.classification, decision: "ALLOW", outcome: "COMPLETED", reason: request.reason, correlationId: request.correlationId, details: { intakeId: request.intakeId, intakeVersion: request.intakeVersion, rawSourceId: request.rawSourceId, rawSourceVersion: request.rawSourceVersion, ...(request.aiResultReference === undefined ? {} : { aiResultId: request.aiResultReference }) } });
    return Object.freeze({ id: candidate.id, version: candidate.version });
  }

  public createOffer(request: Context & { readonly candidateId: string; readonly expectedCandidateVersion: number; readonly transactionType: string; readonly terms: Readonly<Record<string, unknown>>; readonly sourceRefs: readonly ListingReference[] }): ListingOffer {
    const candidate = this.readCandidate(request.candidateId); if (candidate.version !== request.expectedCandidateVersion) throw new Error("VERSION_CONFLICT"); if (request.sourceRefs.length === 0) throw new Error("PROVENANCE_REQUIRED"); this.#authorize(request, "offer.create", "ListingOffer", "new");
    const offer = immutable({ id: this.#idFactory(), version: 1, candidateId: candidate.id, status: "draft" as const, authority: "CANDIDATE_CLAIM" as const, transactionType: request.transactionType, terms: request.terms, sourceRefs: request.sourceRefs, classification: "CONFIDENTIAL_BUSINESS" as const }); this.#offers.set(offer.id, offer); this.#record("LISTING_OFFER_CREATED", "offer.create", offer.id, offer.version, request); return offer;
  }

  public reviseOffer(request: Context & { readonly offerId: string; readonly expectedVersion: number; readonly status: ListingOffer["status"]; readonly terms: Readonly<Record<string, unknown>>; readonly reason: string }): ListingOffer {
    const current = this.#offers.get(request.offerId); if (current === undefined) throw new Error("OFFER_NOT_FOUND"); if (current.version !== request.expectedVersion) throw new Error("VERSION_CONFLICT"); if (request.reason.trim().length === 0) throw new Error("REASON_REQUIRED"); this.#authorize(request, "offer.revise", "ListingOffer", current.id, current.version);
    const updated = immutable({ ...current, version: current.version + 1, status: request.status, terms: request.terms }); this.#offers.set(updated.id, updated); this.#record("LISTING_OFFER_REVISED", "offer.revise", updated.id, updated.version, request, request.reason); return updated;
  }

  public suggestDuplicate(request: Context & { readonly subjectRefs: readonly ListingReference[]; readonly aiResultRef: ListingReference; readonly relationship: string; readonly recommendation: string; readonly signals: readonly string[]; readonly contradictions: readonly string[]; readonly confidence: DuplicateGroup["confidence"] }): DuplicateGroup {
    if (request.subjectRefs.length < 2 || request.signals.length === 0) throw new Error("DUPLICATE_EVIDENCE_REQUIRED"); this.#authorize(request, "duplicate.suggest", "DuplicateGroup", "new");
    const group = immutable({ id: this.#idFactory(), version: 1, status: "DUPLICATE.SUGGESTED" as const, authority: "ADVISORY" as const, subjectRefs: request.subjectRefs, aiResultRef: request.aiResultRef, relationship: request.relationship, recommendation: request.recommendation, signals: request.signals, contradictions: request.contradictions, confidence: request.confidence, decisionHistory: [], classification: "INTERNAL" as const, createdBy: request.actor.principalId }); this.#duplicates.set(group.id, group); this.#record("DUPLICATE_SUGGESTED", "duplicate.suggest", group.id, group.version, request); return group;
  }

  public disposeDuplicate(request: Context & { readonly groupId: string; readonly expectedVersion: number; readonly decision: "NEEDS_EVIDENCE" | "RESOLVED_LINK" | "RESOLVED_MERGE" | "RESOLVED_SEPARATE"; readonly reason: string }): DuplicateGroup {
    const current = this.#duplicates.get(request.groupId); if (current === undefined) throw new Error("DUPLICATE_GROUP_NOT_FOUND"); if (current.version !== request.expectedVersion) throw new Error("VERSION_CONFLICT"); if (request.reason.trim().length === 0) throw new Error("REASON_REQUIRED"); if (request.decision === "RESOLVED_MERGE" && !request.actor.roles.some((role) => role === "SAG" || role === "DST")) throw new Error("SENIOR_REVIEW_REQUIRED"); this.#authorize(request, "duplicate.dispose", "DuplicateGroup", current.id, current.version, current.createdBy);
    const status = `DUPLICATE.${request.decision}` as DuplicateStatus; const entry = immutable({ actorId: request.actor.principalId, decision: status as DuplicateDecision["decision"], reason: request.reason, occurredAt: this.#clock().toISOString() });
    const updated = immutable({ ...current, version: current.version + 1, status, authority: "HUMAN_DISPOSITION" as const, decisionHistory: [...current.decisionHistory, entry] }); this.#duplicates.set(updated.id, updated);
    if (request.decision === "RESOLVED_LINK") this.#linkCandidates(current.subjectRefs);
    this.#record("DUPLICATE_DISPOSED", "duplicate.dispose", updated.id, updated.version, request, request.reason); return updated;
  }

  public readCandidate(id: string): CandidateListing { const candidate = this.#candidates.get(id); if (candidate === undefined) throw new Error("CANDIDATE_NOT_FOUND"); return candidate; }
  public readDuplicate(id: string): DuplicateGroup { const group = this.#duplicates.get(id); if (group === undefined) throw new Error("DUPLICATE_GROUP_NOT_FOUND"); return group; }
  public readCandidateForActor(request: Context & { readonly candidateId: string }): CandidateListing { const candidate = this.readCandidate(request.candidateId); this.#authorize(request, "candidate.read", "CandidateListing", candidate.id, candidate.version); return candidate; }
  public listCandidates(request: Context & { readonly propertyId?: string }): readonly CandidateListing[] { this.#authorize(request, "candidate.read", "CandidateListing", "collection"); return Object.freeze([...this.#candidates.values()].filter((candidate) => request.propertyId === undefined || candidate.propertyRef?.entityId === request.propertyId)); }
  public readDuplicateForActor(request: Context & { readonly groupId: string }): DuplicateGroup { const group = this.readDuplicate(request.groupId); this.#authorize(request, "duplicate.read", "DuplicateGroup", group.id, group.version); return group; }

  #linkCandidates(refs: readonly ListingReference[]): void { const ids = refs.filter((ref) => ref.entityType === "CandidateListing").map((ref) => ref.entityId); for (const id of ids) { const current = this.readCandidate(id); const related = ids.filter((other) => other !== id); this.#candidates.set(id, immutable({ ...current, version: current.version + 1, relatedCandidateIds: [...new Set([...current.relatedCandidateIds, ...related])] })); } }
  #authorize(context: Context, action: string, type: string, id: string, version?: number, createdBy?: string): void { const decision = this.#authorization.evaluate({ session: context.actor, action, resource: { type, id, ...(version === undefined ? {} : { version }), ...(context.actor.teamId === undefined ? {} : { teamId: context.actor.teamId }), ...(createdBy === undefined ? {} : { createdBy }) }, purpose: context.purpose, ...(context.requestId === undefined ? {} : { requestId: context.requestId }), correlationId: context.correlationId }); if (decision.effect === "DENY") throw new Error(decision.reasonCode); }
  #record(eventType: string, action: string, id: string, version: number, context: Context, reason?: string): void { this.#audit.append({ eventType, principal: principal(context.actor), action, target: { type: action.startsWith("duplicate") ? "DuplicateGroup" : action.startsWith("offer") ? "ListingOffer" : "CandidateListing", id, version }, purpose: context.purpose, policyVersion: this.#policyVersion, classification: action.startsWith("duplicate") ? "INTERNAL" : "CONFIDENTIAL_BUSINESS", decision: "ALLOW", outcome: "COMPLETED", ...(reason === undefined ? {} : { reason }), ...(context.requestId === undefined ? {} : { requestId: context.requestId }), correlationId: context.correlationId, details: { authority: action.startsWith("duplicate") ? "ADVISORY_OR_HUMAN" : "CANDIDATE" } }); }
}
